### ISSUE TITLE
blender header

### ISSUE THREAD

**Issue by blender-girl** [kaitai-io/kaitai_struct#1007]
hi

Can I ask why blender 3.4 has in the header of a .blend file '304' instead of '340' ?
Because '304' seems to me 3.04 but '340' is 3.40 ?

see: https://fossies.org/linux/blender/doc/blender_file_format/mystery_of_the_blend.html

**Comment by generalmimon** [comment]
@blender-girl:

> Can I ask why blender 3.4 has in the header of a .blend file '304' instead of '340' ?

I can only work with the available source code of Blender (please consider that I don't know anything about Blender and everything I'll write here is what I've found right now), from which it looks like the version 3.4 would indeed be represented as '304'.

The code reads the 3 characters of the version into a buffer and converts them to an integer using the [`atoi`](https://en.cppreference.com/w/c/string/byte/atoi) function ([`readfile.c:1037-1040`](https://github.com/sobotka/blender/blob/6fc7b37583a2fa0815ae50b8c604f823d863cab1/source/blender/blenloader/intern/readfile.c#L1037-L1040)):

```c
    /* get the version number */
    memcpy(num, header + 9, 3);
    num[3] = 0;
    fd->fileversion = atoi(num);
```

The `fileversion` field is then copied to a field called `versionfile`, for example here ([`readfile.c:4832`](https://github.com/sobotka/blender/blob/6fc7b37583a2fa0815ae50b8c604f823d863cab1/source/blender/blenloader/intern/readfile.c#L4832)):

```c
    mainptr->versionfile = fd->fileversion;
```

And this apparently splits the version integer into individual components ([`rna_main.c:137-139`](https://github.com/sobotka/blender/blob/6fc7b37583a2fa0815ae50b8c604f823d863cab1/source/blender/makesrna/intern/rna_main.c#L137-L139)):

```c
  value[0] = bmain->versionfile / 100;
  value[1] = bmain->versionfile % 100;
  value[2] = bmain->subversionfile;
```

So if you have characters '304' at the beginning, you end up with `value[0]: 3` and `value[1]: 4` here, which suggests version "3.4". '340' would be a different version: 3.40.

> Because '304' seems to me 3.04 but '340' is 3.40 ?

It appears to me that when you get a version string like '304', the integer version components are definitely `3` and `4`, but you have no way of knowing whether it refers to a version called "3.4" or "3.04" (i.e., whether to left-pad the minor version component with a zero or not).

You need to know about the versioning history of Blender to get it right. Looking at https://download.blender.org/release/, '204' would refer to 2.04 (and there is no ~~2.4~~), but '304' refers to 3.4 (and no ~~3.04~~ exists). But the 2.04 version looks like the only one which uses the leading zero, so that's a simple exception to implement.

**Comment by blender-girl** [comment]
Yes, it can be closed! Thanks for the nice explanation.
