### ISSUE TITLE
How to point to a separate data spot in a sequence Kaitai? 

### ISSUE THREAD

**Issue by portconnect** [kaitai-io/kaitai_struct#1036]
I want to build a feature in the .ksy file to reference data from a later data set to satisfy an earlier condition. In the example I included below, it will produce a value of **null** for the x and y fields. The reason is that the condition value is null since the z field comes after the x and y fields. Is there a method that would allow me to bypass this issue? 
```ksy
seq:
 - id: x
   type: b2
   if: z == false
 - id: y1
   type: b1
   if:  z == true
 - id: y1
   type: b1
   if:  z == true
 - id: z
   type: b1
   enum: z_kind
enum:
  z_kind:
  0: false
  1: true
```

**Comment by generalmimon** [comment]
@portconnect:

> The reason is that the condition value is null since the z field comes after the x and y fields.

Yes. Probably in the future the compiler will be able to catch this erroneous situation and provide an error (https://github.com/kaitai-io/kaitai_struct/issues/469), but we're not there yet.

> Is there a method that would allow me to bypass this issue?

That's what `instances` are for. In the example you provided, it's a bit complicated by the fact that the `z` field that you want to use in the condition is a bit-sized integer type (https://doc.kaitai.io/user_guide.html#_bit_sized_integers), which is effectively not supported in `instances` yet (the problem is that there is no support for bit seeking, so the parsing of the bit type when the instance is invoked would permanently change the bit position of the stream and the `seq` parsing would be affected by that - https://github.com/kaitai-io/kaitai_struct/issues/580 is related).

But you can for example read the whole byte and extract the bit you want:

```ksy
seq:
 - id: x
   type: b2
   if: z == z_kind::false
 - id: y1
   type: b1
   if: z == z_kind::true
 - id: y2
   type: b1
   if: z == z_kind::true
 - id: z_old
   type: b1
instances:
  byte0:
    pos: 0
    type: u1
  z:
    value: (byte0 & 0b0010_0000) >> 5
    enum: z_kind
enum:
  z_kind:
    0: false
    1: true
```

Alternatively, you can read always the 2 bits the same way, and then use `value` instances to analyze it further (and note that in your case there's actually no need for the `z_kind` enum, because the 1-bit `type: b1` type in Kaitai Struct is automatically translated to a boolean, see [User Guide](https://doc.kaitai.io/user_guide.html#_basic_data_types): "**Booleans** (...) also can be derived by using `type: b1`"):

```ksy
seq:
 - id: x_or_y
   type: b2
 - id: z
   type: b1
instances:
  x:
    value: x_or_y
    if: not z
  y1:
    value: x_or_y & 0b10
    if: z
  y2:
    value: x_or_y & 0b01
    if: z
```

**Comment by generalmimon** [comment]
No response after my answer - I consider this resolved, closing.
