### ISSUE TITLE
[serialization] [tests] [java]`ci.json` creation obstructed by `checkFoo` unit tests

### ISSUE THREAD

**Issue by izzyreal** [kaitai-io/kaitai_struct#1062]
Reproduction:
```bash
git clone --recursive https://github.com/kaitai-io/kaitai_struct.git && cd kaitai_struct

for module in $(git submodule status | awk '{print $2}')
do
    pushd $module
    git checkout serialization
    popd
done

cd tests && ./build-compiler && ./build-formats && ./ci-java
```
We get something like this:
```
/Users/izmar/git/tmp/kaitai_struct/tests/aggregate/junit_xml_parser.rb:37:in `block (2 levels) in each_test': Unable to parse name: "checkSizeMismatchCheckOrWrite" (RuntimeError)
	from /Library/Ruby/Gems/2.6.0/gems/rexml-3.2.5/lib/rexml/element.rb:1968:in `block in each'
	from /Library/Ruby/Gems/2.6.0/gems/rexml-3.2.5/lib/rexml/xpath.rb:68:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/rexml-3.2.5/lib/rexml/xpath.rb:68:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/rexml-3.2.5/lib/rexml/element.rb:1968:in `each'
	from /Users/izmar/git/tmp/kaitai_struct/tests/aggregate/junit_xml_parser.rb:21:in `block in each_test'
	from /Users/izmar/git/tmp/kaitai_struct/tests/aggregate/junit_xml_parser.rb:19:in `each'
	from /Users/izmar/git/tmp/kaitai_struct/tests/aggregate/junit_xml_parser.rb:19:in `each_test'
	from /Users/izmar/git/tmp/kaitai_struct/tests/aggregate/test_parser.rb:15:in `to_h'
	from aggregate/convert_to_json:77:in `<main>'
```

In `junit_xml_parser.rb` change
```ruby
raise "Unable to parse name: \"#{name}\"" unless name =~ /^[Tt]est(.*?)$/
```
to
```ruby
raise "Unable to parse name: \"#{name}\"" unless (name =~ /^[Tt]est(.*?)$/ || name =~ /^[Cc]heck(.*?)$/)
```
and we can `cat test_out/java/ci.json` again.

This is what I'm doing while working on https://github.com/kaitai-io/kaitai_struct/issues/1060#issuecomment-1656758179.

**Comment by generalmimon** [comment]
At the moment, I almost think the fact that the `ci.json` generation doesn't work for serialization tests for some reason is a good thing, because at least it's clear that our infrastructure isn't ready for them and some work is required to properly support them.

If we only do

```ruby
raise "Unable to parse name: \"#{name}\"" unless (name =~ /^[Tt]est(.*?)$/ || name =~ /^[Cc]heck(.*?)$/)
```

...as you suggest, I guess this will remove the "obstruction" in the `ci.json` generation as you say, but the `check*` tests will be confused as test formats (for the reason I mentioned in https://github.com/kaitai-io/kaitai_struct/issues/1060#issuecomment-1653660227), so I don't see much value in this hack.

In this case, though, calling the test methods just `check*()` without using `test` as a prefix is an unintentional mistake. These tests were written manually and TestNG technically doesn't require that the test methods start with `test` - it uses the `@Test` annotation to distinguish between test and non-test methods. However, [`unittest`](https://docs.python.org/3/library/unittest.html) in Python for example _requires_ that the tests methods start with `test_`, so I had to add the `test_` prefix when porting the manual tests from Java to Python: https://github.com/kaitai-io/kaitai_struct_tests/commit/6a3c0f11d19b26212323c3763d67483752169fa7

So we should actually rename the `check*()` methods to `testCheck*()` in Java for consistency (with Python and with other tests in Java as well), but not to "unobstruct" anything - the `junit_xml_parser.rb` ideally shouldn't care what the test methods are called.
