### ISSUE TITLE
Is it possible to add arbitrary bytes into a (current) stream?

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct#137]
I get the following data from some device, where byte 2 is very likely the same value in most cases. So the sender of the data thought it would be a good idea to remove byte 2 in some cases, where it is absolutely clear that it really has that value, to simply not need to pay for transferring that one additional byte using some mobile M2M communication tariff.

> [5, 1, 2, ...]
> [4, 1, 3, ...]
> [9, 1, 8, ...]

The current approach in my parser for that data is to simply test for if the byte is available in the stream using various conditions and provide it myself using instances else. The problem with that approach is that the byte is never really available in the raw data a parsed stream is based on, but for convenience I simply access that raw data of a stream to store the whole data as read from the device in some database. Because I have a workaround for that behaviour in my parser, it's no problem for me, but it is for other consumers: The data is assumed to follow some standard and with the missing byte it is simply broken regarding that standard and shouldn't be published to others that way.

So I was wondering if there's anything currently in KS which makes me able to add the needed byte depending on some conditions?

I could implement those conditions using some read-ahead approach safely, am doing that already in other places. I simply don't see anything how to do that, but I might be missing something and asking therefore.

If there's nothing available to achieve that, would it make sense to discuss adding something? I think of some `process` or such, simply adding some constant `byte[]` at some place in the created substream. Or do you think this use case is too special/broken to support? It wouldn't fit very well to the stream approach of parsing data, because one would need to read the whole data in memory. Wouldn't be a problem in my case, though, because my `byte[]`s are 255 bytes at max.

**Comment by GreyCat** [comment]
I don't know a lot about your environment, so my first question would be the meaning of "adding the needed byte"?

As far as I've understood, I believe that you want to rewrite the packets somehow to make parsing easier for other consumers? For that, you'll generally need some serialization / generation facilities anyway.

Doing `process` that adds custom byte(s) in certain places of the stream is certainly possible, but I'd probably agree that it's pretty specific case to worth including it into all runtimes, and, of course, if you want *generation* of packets, it won't really help much. It will probably help with simplifying some KS-based code, though.

I might also suggest a slightly alternative approach. Using opaque types, you can basically use it as a loophole to implement any processing you want. Something like that: if your original ksy was like:

```yaml
seq:
  - id: packet_that_needs_byte_2_added
    type: packet
types:
  packet:
    # some crazy tricks to work around byte 2
```

then you can replace that with:

```yaml
seq:
  - id: packet_that_needs_byte_2_added
    type: packet_unmangle
types:
  packet:
    # simpler parsing with not tricks
```

and then you can implement class `PacketUnmangle` using something like that:

```java
public class PacketUnmangle {
    private Packet pkt;

    public PacketUnmangle(KaitaiStream io) {
        byte[] orig = io.readBytes(255); // or whatever you need

        // my crude attempt at insertion of byte at position 1, shifting all array
        byte[] fixed = new byte[orig.length + 1];
        fixed[0] = orig[0];
        fixed[1] = 1; // magically added
        System.arraycopy(orig, 1, dest, 2, orig.length - 1);

        // wrap it again in new KaitaiStream
        KaitaiStream fixedIo = new KaitaiStream(fixed);
        pkt = new Packet(fixedIo)
    }

    Packet pkt() { return pkt; }
}
```

And then, in your Java application, you just do `something.packetThatNeedsByte2Added().pkt()`, and, voila.

But, again, if you need packet generation, it won't help much.

**Comment by tschoening** [comment]
> I don't know a lot about your environment, so my first question would be the meaning of "adding the
> needed byte"?

I get for example the following three telegrams, where the second one misses the needed byte. And the only thing I would like to do is "somehow" add the one single byte at its place before parsing the whole stuff.

> [5, 1, 2, ...]
> [4,     3, ...]
> [9, 1, 8, ...]

to

> [5, 1, 2, ...]
> [4, 1, 3, ...]
> [9, 1, 8, ...]

The important thing is that I can easily access the substream a parsed structure is based on during runtime to write the raw data into the database. I don't need to pass that somewhere on my own, just forward my parsed structures everywhere I need them. And that raw data is missing my byte currently, because it's not there obviously :-), even if it is available accessing the structure because of `instances` providing it and such. By design I decided to store only raw, unchanged data in the database, without any workarounds applied during runtime. That one missing byte now is an exception...

I don't need any more fancy serialization or generation of packets, that's why I thought of some easy approach based on `process`. That way I could apply a workaround and keep the substream-approach to write it back into the database.

The problem with your suggestion is that I currently heavily use your Ruby visualizer, it makes life really easier, and that wouldn't be possible anymore if some parts are implemented in Java only. I would need to do the same with Ruby and in the end that comes really close already to implement it in the runtimes for target languages. :-)

So, would you refuse to add something like `process: insertBytes(1, [1])` at all? Else I might look into this in future and might provide a PoC.

**Comment by koczkatamas** [comment]
My main concern is that with every new feature we implement into Kaitai we make a commitment that feature won't break in the future versions (especially if we hit the version 1.0 as if I understood correctly we want to provide strong backward compatibility from that version onward).

If we want to keep our promise then it can slow down the evolution of the whole Kaitai project if we spend time with fixing rarely used features instead of implementing new, important / often used ones.

On the other hand I don't want to discourage advancement either, but I think for rarely used features (I presume this is one of them, but fix me if I am wrong) we should make a clear statement that those features won't be supported at the same level as our "main" features. So for example they can broke from one release to another and may not be fixed in the near future.

I don't know the good solution for this problem, but a few ideas came into my mind:
 - some kind of plugin support
 - disable these features by default and you can allow them with an --experimental-features flag, so you'll hopefully think twice before start using these features
 - some kind of embedded programming language where you can write down the code in the ksy file, not in the compiler and then it can compile into different languages

Sadly none of my ideas are easy to implement (maybe the second one is the closest) and their usability / abuse-ability is also questionable.

Hmmm how about implementing the custom functionality in a custom "opaque" class (one implementation for every language you use: one for Java, one for Ruby) and put these implementations into the formats repo as non-ksy, but "native" implementation?

This is halfway implementing a plugin support, and the custom Kaitai programming language. It can be part of the main distribution (as part of the formats repo), but on the other hand we don't have to maintain compatibility that much.

**Comment by tschoening** [comment]
I totally understand your concerns and yes, I see this to be a very special and rarely used case. We don't even need to do anything right know, I'm not even working on this problem currently. It's just something I have on the TODO list and was thinking about.

That plugin support sounds like a good direction to think of to me. Especially as it has been [discussed](https://github.com/kaitai-io/kaitai_struct/issues/51) already in the past. I don't see how a native type in the formats repo for what I need makes sense for others. You are starting mixing native and pure KSY implementations of types this way as well, which doesn't sound that good to me.

I like the idea of enhancing `process` to "simply" being able to call some custom function in some class. Like with current `processes`, one doesn't need to provide any status at all at first, only some bytes as stream or array, maybe some args as well. This way you could already support the available implementations of zlib, xor etc. and everyone could add their own as needed. I would have the need for some other Zip support already as well, even some decryptions might be possible, like suggested in #51.

Like with the formats repo, you could create some `processes` or `processors` or ... repo, where you could store things under common names which you don't want to have in runtimes and don't want to support. People could easily fork that repo and provide their own contributions as needed.

With all the new import stuff and such, wouldn't that be a reasonable way to go? Sounds more close to a future plugin system as well. And might be stripped down as far as possible to only need to care about how to externally call what is currently called in the runtimes. This addresses at least some of your former mentioned [concerns](https://github.com/kaitai-io/kaitai_struct/issues/51#issuecomment-260882407) as well.

**Comment by GreyCat** [comment]
Ok, let's try to separate this stuff into a few distinct areas.

Point 1: adding stuff like `process: insertBytes(1, [1])`. Generally, all that "process" things are completely unexplored and undeveloped territory. To be frank, that's one of the things I'm really not happy about in KS language design — they look really clunky, they add some extra hideous syntax *in addition* to normal expression language, etc, etc. Actually, they predate whole expression language business, and, especially in their current form, they have much less potential than expression language.

Currently, I see their place as a way to call native, efficient implementations of well-known algorithms — compression, encryption, etc. I think that there's no point in inventing yet another generic data conversion language in `process` syntax. I'm not even completely sure that we shouldn't get rid of `process` stuff and replace it with simple value instances and byte array methods. Something explicit like:

```yaml
seq:
  - id: buf_encrypted
    size: 0x100
instances:
  buf_decrypted:
    value: buf_encypted.xor(0xaa)
```

Obviously, that has its cons:

* it's too verbose
* it's much harder to reverse when we'll be doing serialization
* it has some problems with instancing some type in `buf_decrypted`: we either need to introduce a user type constructor call into expression language or add some more `type`-supporting syntax on top of calculated byte arrays

So, given that I can't see a clear way, I'd rather accept responsibility only for the stuff in `process` that I'm 100% sure that it's needed everywhere, reusable, there are efficient native implementations of that algorithm, etc. That's why #45 would still probably be implemented sooner or later.

Adding random stuff to `process` is generally a bad idea. There's only a single name, no namespaces, no nothing. We'll end up with a huge mess of "useful methods", like one they have in PHP or Perl, for example. Inventing some byte array processing language here would require *a lot* of planning and effort, it can't be done "one step at a time" by adding functions like "insertBytes", "deleteBytes", etc. And, to repeat myself, in my opinion, inventing 2nd language is a bad idea anyway — we should rather invest our potential into a single expression language as a *generic* way to go.

That said, point 2: custom processing routines. Actually, I quite like the idea of providing a way to call something like unified "interface" that would implement a certain processing. Something like:

```yaml
seq:
  - id: code
    type: u4
  - id: buf
    size: 0x100
    process:
      class: my_custom_processing
      params:
        - 4
        - code
```

This would generate something like that in Java:

```java
        this.code = this._io.readU4le();
        this._raw_buf = this._io.readBytes(256);
        this.buf = MyCustomProcessing.unpack(this._raw_buf, 4, code());
```

The only thing that's left is to implement `MyCustomProcessing` class that will have relevant `unpack(...)` method. Unfortunately, we can't really have a "real" interface here, as `unpack` / `pack` arguments would be different for every method, but that should still work by convention.

Running it with visualizer(s) probably won't be that hard too: we should provide some extra settings / command line switches to preload certain classes (like MyCustomProcessing.rb or MyCustomProcessing.js), so they would be usable from inside the visualizer.

**Comment by tschoening** [comment]
It's time to close this, it started with a question only and KS provides custom processing routines by now:

http://doc.kaitai.io/user_guide.html#custom-process

**Comment by GreyCat** [comment]
Thanks!
