### ISSUE TITLE
Exponential floating point literals with non-integral part

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#175]
As reported in https://github.com/kaitai-io/kaitai_struct/issues/174#issuecomment-301798344, currently our expression language fails to parse floating point literals with exponential part + non-integral part, i.e. something like `1.234e-5`. This is clearly a bug, as basically everything else around parses this form correctly.

**Comment by GreyCat** [comment]
Seems to be fixed in https://github.com/kaitai-io/kaitai_struct_compiler/commit/52992b79f997bbb0d1a3805c91fa7ecf0c1e7fca — @JaapAap, could you please take a look if it works for you now?

**Comment by JaapAap** [comment]
I have manually updated lexical.scala and that indeed resolved the parsing issue, thanks. I saw that in  ExpressionsSpec.scala there are also some tests that use casting of literals but I was unable to use these getting complaints about missing types - possibly because my files are out of sync? In any case, compiler issue 62 (CalcIntType "int" might lead to loss of data (in Java) ) seems to be related to this - it seems to me that there will always be a need to assist the type deduction system. Currently, when using the following code:

```
instances:
  a:
    value: unscaled_a*8
```

I observe that` a` becomes a 32-bit (signed) integer, which does not always work, In many cases I would indeed need `a` to be of a wider type than `unscaled_a`, as well as needing it to be unsigned. This seems a situation that is likely to occur often, as the unscaled value is stored in the binary format in a smaller amount of bits than would be needed for `a` to make the binary format as efficient as it can be. Hence, the solution in issue 62  (to use as wide an int as possible) has some merits, but sometimes an unsigned result is desired or it would be known to the user that a smaller integer would do.

**Comment by JaapAap** [comment]
Thanks - doing it manually seemed the easiest way to quickly merge the update into my own version of the compiler to allow testing it on actual ksy's that also need the new bitfield types (admittedly, I am new to git so might be missing something here)... Would it be maybe possible to add a `type:` entry into the instances to override the type inference engine's results? 

BTW, when applying `as<u4>` on aI actually get the message   /instances/toe/value: unable to find type 'u4' - parenthesis don't seem to make much difference , doing something like this:

```
instances:
  pot:
    type: powers_of_two // imports powers of two
  a:
    value: unscaled_a*(pot.two_to_power_4).as<u4>
```

**Comment by GreyCat** [comment]
> Would it be maybe possible to add a `type:` entry into the instances to override the type inference engine's results?

There are several problems here:

1. `type` does not really map to a target language concept of type 1-to-1. For example, byte array of 16 bytes is defined as `size: 16`, not with any `type: xxx`. There are two "string" types, i.e. `str` and `strz`, both of which represent strings, etc, etc. If you'd want to generate an array, you need to add `repeat: xxx`, but then again, all the repeat values only make sense when we're talking about serialization/deserialization, and are useless in abstract context of value calculation.
2. Even if we'll add it somehow, the core problem is not in type inferring engine. Doing stuff like `one_int32 * another_int32` which results may be potentially larger than int32, and thus should be upscaled to int64 (or even to a bigint in most dynamic languages) indeed requires some manual type casting — i.e. you actually need to upscale each individual int32. I.e. generating stuff like `(int64_t) (one_int32 * another_int32)` is possible, but wrong anyway.

**Comment by GreyCat** [comment]
> BTW, when applying as<u4> on aI actually get the message /instances/toe/value: unable to find type 'u4'

This is exactly what I've mentioned as "we don't support type casting of primitives (only user-defined types)". If tries to find a user-defined type named "u4" and fails to do it.
