### ISSUE TITLE
_root doesn't refer to the true root

### ISSUE THREAD

**Issue by jcreigh** [kaitai-io/kaitai_struct#217]
If you have a project that is split between many ksy files, you can't access the entire tree using _root or _parent.

They stop at the top of the current file instead of being able to access what's above.

If this wasn't an oversight, then I suggest adding a way to access the true root.

**Comment by GreyCat** [comment]
This is more or less by design. The idea is that files are not supposed to be used just a way to split a big project into many files, but rather the emphasis is on that each file is supposed to be a complete logical unit. Basically, if file A imports file B, then you can always compile file B separately (using `ksc [...] b.ksy`) and get the exact same result as when compiling it together with A (using `ksc [...] a.ksy b.ksy`).

To get around that, you can use [new parametric types](https://github.com/kaitai-io/kaitai_struct/issues/192) syntax, explicitly passing some parameters into the types declared in distinct files.
