### ISSUE TITLE
Implement variable-length integer type

### ISSUE THREAD

**Issue by crackedmind** [kaitai-io/kaitai_struct#256]
Varint encodings use only the bytes that are needed to represent you integer value appropriately. A varint algorithm can represent the number 10 in only one byte while using 4 bytes to encode 800000000 (800 million).

It is widly used, in protobuf, in .Net binary reader/writer (known as 7-bit encoded int), etc.

**Comment by GreyCat** [comment]
There are tons of variations of such encodings. The most popular versions of it are already implemented as  [vlq_base128_be](http://formats.kaitai.io/vlq_base128_be/) and [vlq_base128_le](http://formats.kaitai.io/vlq_base128_le/). And, yeah, we do use them in [protobuf](http://formats.kaitai.io/google_protobuf/).

**Comment by GreyCat** [comment]
> Is VarInt parsing effectuated by native function or by a schema?

By schema. Indeed, in some cases probably native implementation would be more efficient.

> Note that VarInt allows storing arbitrarily large numbers which are in some languages (C and C++).

Yes, and that is also a problem: current schema implementations only handle up to 8 byte integers, and even that is so-so (for example, JavaScript has hard limit on 32 bits for all bit shifts).

**Comment by arekbulski** [comment]
This is a larger issue so I should probably open a new thread for it, but oh well. I think the solution would be to add "selective impl" to Kaitai, so in code gen, each type (like varint) would either be using native impl (if available for that field for that lang) or schema impl otherwise. This way we could add VarInt impl only to one language, iron it out, then port it to those langs where it matters. I suppose that C code gen would benefit the most from this feature. And then what you said would no longer be the case, we would not need 11 implementations for varint. Only 1 or 2. What do you think @GreyCat ?

**Comment by GreyCat** [comment]
Closing this one, as current answer stands, and it seems to be viable solution for time being.
