### ISSUE TITLE
Use git lfs in kaitai_struct_tests for binaries

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#258]

**Comment by GreyCat** [comment]
Any rationales?

So far, I see only lots of problems:

* git lfs is GitHub-specific.
* It is non-standard and requires manual installation.
* It makes user experience *much* harder.
* It makes Travis CI usage *much* harder (as it checks out repos automatically).
* I have no idea how it works with git submodules (and I won't be surprised if the answer is "it doesn't work with submodules").
* It does not really bring any benefits, as binaries in kaitai_struct_tests are very small by design.

**Comment by KOLANICH** [comment]
>git lfs is GitHub-specific.
not quite: gitlab and bitbucket also support it

>It is non-standard and requires manual installation.
for Windows  it is shipped with ```GIT For Windows```
for linux there are packages for debian and ubuntu (17.10) in official repos
for earlier ubuntu there are packages in an unofficial one

>It makes user experience much harder.
It automatically tracks the files matching patterns once set up.

>It makes Travis CI usage much harder (as it checks out repos automatically).

https://docs.travis-ci.com/user/customizing-the-build#Linux
>Git LFS is supported by default on our Ubuntu Trusty images.


>I have no idea how it works with git submodules (and I won't be surprised if the answer is "it doesn't work with submodules").
I guess it should work as it hooks some git operations. But I have not tested that for now.

>It does not really bring any benefits, as binaries in kaitai_struct_tests are very small by design.

Maybe. Have not measured the overhead.

**Comment by GreyCat** [comment]
Ok, let's get back to this once there would be any substantial evidence that we need this.
