### ISSUE TITLE
Compiler: selective schema/native implementation

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#312]
I propose that we change how compiler handles fields that are currently schema-implemented eg. varint. For each field, compiler should have a set of runtimes that have native-implementation. This way same field can be natively implemented in few (very few) runtimes. Compiler would on each field, either defer to KaitaiStruct (if native-impl exists) or to schema (if doesnt). Each runtime would implement a different superset of a common minimum.

Runtimes that are expected to have high performance would use this feature more than others. 

Also, this touches the problem of missing types in certain runtimes (eg. bigints). VarInt schema-impl uses 8 bytes, native-impl would be free to implement arbitrary amount. This could create inconsistency in field semantics between runtimes, so a decision should be made in advance should all native implementations have same semantics or not.

**Comment by KOLANICH** [comment]
#126,

**Comment by arekbulski** [comment]
I think #126 tries to extend everything with plugins (while solving the "we surely shouldn't embed everything in the world into KS comtranspiler and runtimes" problem). Much broader in scope than what I suggest.

**Comment by GreyCat** [comment]
There would be several major hurdles to jump over while implementing this one:

## Schema implementations are not "seamless"

Current "schema implementations" are not exactly "seamless", i.e. you can't just start with:

```yaml
seq:
  - id: some_custom_int
    type: vlq_base128_be
```

and then have:

```yaml
instances:
  same_int_doubled:
    value: some_custom_int * 2
```

Instead, you're bound to use `.value`

```yaml
instances:
  same_int_doubled:
    value: some_custom_int.value * 2
```

And even that is not a standard, just some common thing that these implementations use. So, `some_custom_int` continues to be of user type. There was a proposal to at least make standard way to use these schema-backed implementations in the same context as normal integers and other values — for example, by agreeing on some sort of special field name like `_value`, or `_int`, or `_to_i`, or something like that — if that is present, then aforementioned schema-backed type could be used in normal integer context.

I recall that there was some issue about that, yet I can't find it right now :(

## Allowing native implementations by using some sort of plugin system

This is what's generally discussed in #188 — we can't really put everything into our runtime & compiler, so that's bound to be a plugin. Currently, viable way seems to be supplying some native code + some declaration/header for ksc that would inform ksc about existence of native-backed type. This can be used to output both more intricate types like bitmaps, matrices and numpy arrays, but it could work with simpler integers as well.

## Some switching code to unify them together

Finally, after both sides are complete, we could glue them together with some switching code. That's also probably a big discussion, as that would require introduction of some "glue" declarations.

**Comment by arekbulski** [comment]
Construct has a `FocusedSeq` wrapper that is similar to `_value` feat that you describe. 
https://construct.readthedocs.io/en/latest/misc.html#focusedseq

I would like to see `_value` feat added to Kaitai.

**Comment by arekbulski** [comment]
Construct has a `FocusedSeq` wrapper that is similar to `_value` feat that you describe. 
https://construct.readthedocs.io/en/latest/misc.html#focusedseq

I would like to see `_value` feat added to Kaitai. 

Also would like to point out that native-impl of varint could simply result in a struct with a value field, instead of an integer. This would make schema- and native- implementations seamless.

**Comment by arekbulski** [comment]
I think that the consensus could be summarized as: there is no real need for this feature.
