### ISSUE TITLE
Windows DIB format in bytearray to image?

### ISSUE THREAD

**Issue by paulopires16** [kaitai-io/kaitai_struct#398]
I have OLE Object in bytearray that I intent to write to disc: https://ufile.io/5mnfn
How to convert this info (Windows DIB) to image with kaitaistruct?
Thanks

**Comment by KOLANICH** [comment]
dib is bmp.

**Comment by paulopires16** [comment]
Yes, I now. I have that image, see the link. I write it but can't open...
That image was copied with keyboard to ole objects data source

**Comment by paulopires16** [comment]
I read that ole object with that image bytearray info into a variable. Then I just try to write to disc...
Something is missing...

**Comment by tschoening** [comment]
> Can I convert them to BMP with kaitaistruct ?

I'm not sure I understand your problem, but KS is not a converter of different file formats in the first place. It's a generator for a parser which allows you to access individual parts of your data by some meaning in the end. So yes, you can write such a parser for your file format to access individual and use that in some kind of format conversion you build on your own using that parser. But no, KS will not provide you with some DIB-input method and create some BMP-output for you automatically.

But from what I've read and how I understand @KOLANICH, implementing such a conversion shouldn't be necessary, because a DIB file seems to be compatible with a BMP file.

**Comment by KOLANICH** [comment]
@paulopires16, Do you know what abstract syntax tree is? It is an object representation of source code.
For example
```python
from b import a
b=a(1+2)
```
will give the following AST
```python
ImportFrom(module='b', names=[alias(name='a', asname=None)], level=0), Assign(targets=[Name(id='b', ctx=Store())], value=Call(func=Name(id='a', ctx=Load()), args=[BinOp(left=Num(n=1), op=Add(), right=Num(n=2))], keywords=[], starargs=None, kwargs=None))
```

A parser is a program building an AST from source. A parser is generated from grammar writted in special programming language.

Now imagine that binary string is the source. Then all the KSYs used is the grammar, and the code compiled from them is parser. You apply this parser to binary and get an AST of that binary. If you wanna get pixels values you will have to parse a file with the parser and some part of AST should have something which can be converted into pixels values.

**Comment by KOLANICH** [comment]
Here is the example for NT MDT format https://github.com/KOLANICH/NTMDTRead/blob/master/examples/show.py

**Comment by paulopires16** [comment]
Thanks
I already found a solution yesterday. My problem was ther header...

`
# byte array image
data = row[i]
data[:57] = str('\x42\x4D\xDA\x82\x15\x00\x00\x00\x00\x00\x36\x00\x00\x00') # bmp header
data = data[:len(data)-4]
`
