### ISSUE TITLE
CSharp runtime: mutating data in process xor/rotate

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#406]
I am looking at C# runtime, particularly at `ProcessXor` and `ProcessRotateLeft` methods. Would it be acceptable if those methods mutated the data bytearrays instead of allocating new arrays?

On side note: would it be acceptable if those methods were marked as `unsafe`?

**Comment by koczkatamas** [comment]
If you mark this code `unsafe` then the user have to mark his/her whole application `unsafe` which is not really acceptable IMHO. Also it probably brings us further from supporting portable class libraries, which can also be a drawback.

The first question is probably better answered by @GreyCat. If we don't need the original array ever again, then it's probably okay, but we should make a bold warning in the method comments, because with this method signature (returning `byte[]`) I would expect them NOT to modify the array in-place.

**Comment by arekbulski** [comment]
I suspect that some tags like `size+processxor` are compiled into a code that would have no issue with mutating the data, but if you have a separate field and then processxor it in a second field (if that is even possible?) then it could not mutate safely. But I would have no problem with adding an optional parameter to the method, and implement it both ways.

**Comment by arekbulski** [comment]
I suspect that some tags like `size+processxor` are compiled into a code that would have no issue with mutating the data, but if you have a separate field and then processxor it in a second field (if that is even possible?) then it could not mutate safely. But I would have no problem with adding an optional parameter to the method, and implement it both ways.

The reason for adding `unsafe` is that so I could use `fixed` statement for GC-pinning the bytearrays, which would allow me to make heavy performance optimisation. If you wonder how much performance could be added, [see this](https://stackoverflow.com/questions/33294580/sse-instruction-to-check-if-byte-array-is-zeroes-c-sharp) for comparison (334 vs 25).

**Comment by arekbulski** [comment]
The original topic is closed.

**Comment by GreyCat** [comment]
> On side note: would it be acceptable if those methods were marked as `unsafe`?

Definitely not in a general-purpose library. If you want to implement one, you can actually easily implement a custom unsafe xor processor for .NET just by implementing a custom decoder interface.
