### ISSUE TITLE
Referencing _index in the pos attribute of a repeated instance produces: undefined local variable or method `i'

### ISSUE THREAD

**Issue by tmillican** [kaitai-io/kaitai_struct#436]
Here's about the simplest example of the problem I could come up with. This is almost verbatim the second example in [7.9. Repetition index](http://doc.kaitai.io/user_guide.html#repeat-index). I've just made things shorter by using `u1` instead of `u4`, and removing the `file_names` item.

`files.ksy`:

    meta:
      id: files
    seq:
      - id: num_files
        type: u1
      - id: len_files
        type: u1
        repeat: expr
        repeat-expr: num_files
      - id: ofs_files
        type: u1
        repeat: expr
        repeat-expr: num_files
    instances:
      file_bodies:
        pos: ofs_files[_index]
        size: len_files[_index]
        repeat: expr
        repeat-expr: num_files

And we want to use this on `files.bin`:

    00000000: 02 05 04 0a 13 00 00 00 00 00 61 62 63 64 65 00 | ..........abcde.
    00000010: 00 00 00 77 78 79 7a                            | ...wxyz

When you run `ksv files.bin files.ksy`, everything is initially fine. But when you try to expand the `file_bodies` node, you get:

    files.rb:42:in `file_bodies': undefined local variable or method `i' for Files(num_files=2 len_files=[5, 4] ofs_files=[10, 19]):Files (NameError)

If you compile to Ruby, it's obvious what's wrong:

      def file_bodies
        return @file_bodies unless @file_bodies.nil?
        _pos = @_io.pos
        @_io.seek(ofs_files[i])
        @file_bodies = Array.new(num_files)
        (num_files).times { |i|
          @file_bodies[i] = @_io.read_bytes(len_files[i])
        }
        @_io.seek(_pos)
        @file_bodies
      end

It seems `ksc` interprets the `pos` attribute as outside of the repetition loop, when it should be inside. I've only looked at the Ruby, Java and CSharp output, but it seems to be doing this in all target languages.

**Comment by tmillican** [comment]
Incidentally, here is a simple workaround, if you don't mind having the equivalent of a non-semantic &lt;div&gt;:

    instances:
      file_bodies:
        type: file_body(_index)
        repeat: expr
        repeat-expr: num_files
    
    types:
      file_body:
        params: file_index
        type: s4
      instances:
        body:
          pos: _parent.ofs_files[file_index]
          size: _parent.len_files[file_index]

**Comment by fallenoak** [comment]
I just bumped into this issue when writing a parser. I'd really love to avoid wrapper types if possible.

@GreyCat What do you think of @tmillican's proposal for a `repeat-pos` addition?

**Comment by generalmimon** [comment]
> What do you think of @tmillican's proposal for a `repeat-pos` addition?

I consider this useless, inlining is better and more generic solution. Something similar was proposed in https://github.com/kaitai-io/kaitai_struct/issues/119 (a `repeat-size` key), but I'm convinced that all such efforts are going the wrong way. If we would choose that way, we'd have to invent lots of "new" properties (`repeat-pos`, `repeat-size`) that work exactly the same as their primitive counterparts (`pos`, `size`), with the only difference that it isn't needed to create a wrapper type in some specific case. We should always try to provide general solutions that work in many cases rather than solving each specific case separately.

> Low priority, obviously, but it would be nice not to have "wrapper" types like this when you use that approach.

> I'd really love to avoid wrapper types if possible.

Apparently the same problem as #88.

However I think that the current behavior of the compiler can be improved: it probably shouldn't be possible to use `_index` in `pos` at all. This could end up with an compile error. Would it make sense or is it a bad idea? What do you think?

After resolving this I'll close this issue, as the inlining (#88) can solve this.
