### ISSUE TITLE
How do you install Kaitai Struct for python ?  I couldn't find it with pip

### ISSUE THREAD

**Issue by enjoysmath** [kaitai-io/kaitai_struct#439]
So the installer ends and the only way I can find what it installed is to do a windows search.

But that didn't turn up anything, so I manually found (part of) it under Program Files (x86).

No python files inside that directory.

I'm not sure how to get 

from kaitaistruct import KaitaiStream, BytesIO

to work.

Thanks.

**Comment by KOLANICH** [comment]
```pip install --upgrade kaitaistruct```

**Comment by GreyCat** [comment]
> So the installer ends and the only way I can find what it installed is to do a windows search.

That's not true. Installer offers you an option to change installation path, and clearly shows it during the process:

![image](https://user-images.githubusercontent.com/157154/40302012-bbefcc4c-5ce5-11e8-9ff9-66a0f5da9b92.png)

Moreover, on the same options page, you agree that it changes your PATH environment var to include "kaitai-struct-compiler" to be available everywhere in command line.

> But that didn't turn up anything, so I manually found (part of) it under Program Files (x86).

It's not "part", it is whole *compiler*. To get the target running in different languages, you would need compiler/interpreter of that language (i.e. Python in your case) and Kaitai Struct runtime (which we can't install easily, because Windows world is, unfortunately, very chaotic about installation locations). There are tons of other scenarios when you won't need all the runtimes anyway.

**Comment by GreyCat** [comment]
Closing this one due to inactivity. Feel free to reopen if any questions still remain.
