### ISSUE TITLE
Wrong output for ksc-json-output in case of relative paths under Windows.

### ISSUE THREAD

**Issue by ams-tschoening** [kaitai-io/kaitai_struct#507]
I upgraded `ksv` to get support for [opaque types](https://github.com/kaitai-io/kaitai_struct_visualizer/issues/15) and with it came a changed interaction with `ksc`, the new `ksc-json-output` is used now. This leads to compile time errors in `ksv` for me, because your generated JSON doesn't seem to handle paths and their different representation in Java under different OS correctly. 

> C:/[...]/visualizer_main.rb:68:in `block (2 levels) in compile_formats': undefined method `[]' for nil:NilClass (NoMethodError)
        from C:/Program Files (x86)/kaitai_struct/visualizer/lib/kaitai/struct/visualizer/visualizer_main.rb:64:in `each'
        from C:/Program Files (x86)/kaitai_struct/visualizer/lib/kaitai/struct/visualizer/visualizer_main.rb:64:in `each_with_index'
        from C:/Program Files (x86)/kaitai_struct/visualizer/lib/kaitai/struct/visualizer/visualizer_main.rb:64:in `block in compile_formats'

``` Ruby
      fns.each_with_index { |fn, idx|
        puts "... processing #{fn} #{idx}"

        log_fn = log[fn]
        if log_fn['errors']
```

``` JSON
{"record\fmt_clt_recs.ksy": {"firstSpecName": "fmt_clt_recs","output": {"ruby": {"fmt_clt_recs": {"topLevelName": "FmtCltRecs","files": [{"fileName": "fmt_clt_recs.rb"}]},"fmt_oms_rec": {"topLevelName": "FmtOmsRec","files": [{"fileName": "fmt_oms_rec.rb"}]}}}},"record\fmt_oms_rec.ksy": {"firstSpecName": "fmt_oms_rec","output": {"ruby": {"fmt_oms_rec": {"topLevelName": "FmtOmsRec","files": [{"fileName": "fmt_oms_rec.rb"}]}}}}}
```

There are two problems here:

1. / to \

I use a command line similar to the following in Eclipse to start `ksv`:

> [...]ksv "${workspace_loc}/[...]/data.bin" "record/fmt_clt_recs.ksy" "record/fmt_oms_rec.ksy"

With the current `ksc` this leads to `\` instead of `/` in the generated JSON object, because Java internally uses a platform dependent path separator most of the times. The problem is that `ksv` sees `/` itself and can't find its own paths in the JSON anymore. I used `/` in favour of `\` simply because I had trouble using `\` in the past and `/` seems to be more common in Ruby, this would work on non-Windows etc.

2. Improper escaping of \

`\` needs to be escaped in JSON, that's why changing `/` to `\` in my invocation above doesn't fix the problem: JSON contains `\f` in the end instead of `\\f` which is what Ruby internally would have as the String key.

In my opinion, the best thing to do is simply to not generate `\` in JSON at all, so that only one normalized path separator is used across platforms and languages:

	  // FIXME: do proper string handling
	  def stringToJson(str: String): String =
	    "\"%s\"".format(str.replaceAll("\\\\", "/"))

This is somewhat hacky as well of course, but fixes the escape problem and makes interacting with `ksv` easier.

**Comment by generalmimon** [comment]
Although the main problem of this issue (invalid string literals like `"path\to\format.ksy"` in the JSON output) has been resolved in KSC 0.8, there is still the compiler's behavior of converting input paths with `/` to `\` in the `--ksc-json-output` report on Windows to discuss. As of KSC 0.10, the compiler still converts the path to backslashes even if the input .ksy path uses forward slashes (notice the second test, where the compiler used `".\\hello_world.ksy"` as JSON key even though `./hello_world.ksy` was given as the input path):

```
C:\temp\ksc-json-output-tests>kaitai-struct-compiler --ksc-json-output -t ruby -d test-a1 hello_world.ksy
{"hello_world.ksy": {"firstSpecName": "hello_world","output": {"ruby": {"hello_world": {"topLevelName": "HelloWorld","files": [{"fileName": "hello_world.rb"}]}}}}}

C:\temp\ksc-json-output-tests>kaitai-struct-compiler --ksc-json-output -t ruby -d test-a2 ./hello_world.ksy
{".\\hello_world.ksy": {"firstSpecName": "hello_world","output": {"ruby": {"hello_world": {"topLevelName": "HelloWorld","files": [{"fileName": "hello_world.rb"}]}}}}}

C:\temp\ksc-json-output-tests>kaitai-struct-compiler --ksc-json-output -t ruby -d test-a3 .\hello_world.ksy
{".\\hello_world.ksy": {"firstSpecName": "hello_world","output": {"ruby": {"hello_world": {"topLevelName": "HelloWorld","files": [{"fileName": "hello_world.rb"}]}}}}}
```

Personally, I see this as somewhat unfortunate behavior and don't see any benefit in it. I think reflecting the original .ksy path exactly as passed on the command line to `kaitai-struct-compiler` (i.e. without any slash conversions or anything else) in the JSON output is the least surprising behavior that would make KSC very easy to use: the naive way of using the input .ksy path directly as a key to the JSON object simply always works regardless of what slashes were used, what platform we're on, etc.

@ams-tschoening:

> I use a command line similar to the following in Eclipse to start `ksv`:
> 
> > [...]ksv "${workspace_loc}/[...]/data.bin" "record/fmt_clt_recs.ksy" "record/fmt_oms_rec.ksy"
> 
> With the current `ksc` this leads to `\` instead of `/` in the generated JSON object, because Java internally uses a platform dependent path separator most of the times. The problem is that `ksv` sees `/` itself and can't find its own paths in the JSON anymore. I used `/` in favour of `\` simply because I had trouble using `\` in the past and `/` seems to be more common in Ruby, this would work on non-Windows etc.

I reported this problem (without knowing about _this_ issue) in https://github.com/kaitai-io/kaitai_struct_visualizer/issues/52 and worked around it in `ksv` in https://github.com/kaitai-io/kaitai_struct_visualizer/commit/d9a3dbdc6c06ffd47c94e9f012802b0d61b68af9. Retrying the path with all forward slashes `/` replaced to backslashes `\` seemed to work in simple cases I happened to test, but admittedly, it was a hack without properly investigating the cause of the problem. The simplest proper fix I see would be to just change the compiler to use the input path strings exactly as JSON keys, so that `ksv` (and possibly other third-party applications making use of `--ksc-json-output`, if they exist) can reliably look them up in the JSON 100% of the time.

**Comment by generalmimon** [comment]
Apparently, the reason why the compiler converts the input paths is because it initially reads the given command-line .ksy path arguments to [`java.io.File`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html) objects (see [`JavaMain.scala:38`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/7071a9de11de3bafa711b6eb21961bbf7680623a/jvm/src/main/scala/io/kaitai/struct/JavaMain.scala#L38)) and later uses their [`toString()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#toString()) method to convert the `File` objects back to path strings ([`JavaMain.scala:279`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/7071a9de11de3bafa711b6eb21961bbf7680623a/jvm/src/main/scala/io/kaitai/struct/JavaMain.scala#L279)). However, [`toString()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#toString()) uses the `getPath()` method:

> <code>public <a href="https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html">String</a> toString()</code>
> 
> Returns the pathname string of this abstract pathname. This is just the string **returned by the [`getPath()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#getPath()) method.**

and [`getPath()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#getPath()) is specified to use the system-dependent separator character:

> <code>public <a href="https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html">String</a> getPath()</code>
> 
> Converts this abstract pathname into a pathname string. The resulting string uses the [`default name-separator character`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#separator) to separate the names in the name sequence.

... which is specified as follows ([`separatorChar`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#separatorChar)):

> `public static final char separatorChar`
> 
> The system-dependent default name-separator character. This field is initialized to contain the first character of the value of the system property file.separator. **On UNIX systems the value of this field is `'/'`; on Microsoft Windows systems it is `'\\'`.**

Also, according to my tests, it also collapses multiple consecutive slashes into one (this is in WSL 2, happens on Windows as well):

```console
$ kaitai-struct-compiler -- --ksc-json-output -t ruby -d test-wsl .///hello_world.ksy
{"./hello_world.ksy": {"firstSpecName": "hello_world","output": {"ruby": {"hello_world": {"topLevelName": "HelloWorld","files": [{"fileName": "hello_world.rb"}]}}}}}
```

Which further proves that merely retrying the path with `/` replaced by `\` as the JSON key that I added in https://github.com/kaitai-io/kaitai_struct_visualizer/commit/d9a3dbdc6c06ffd47c94e9f012802b0d61b68af9 was a band-aid solution, not a proper fix.

**Comment by generalmimon** [comment]
@ams-tschoening:

> Don't you think normalizing paths would be worth another hack? JSON itself is OS-independent, so providing such paths as well seems the right thing to do. We do that in some of our software as well for different runtimes and OS like Perl, which automatically convert `/` to `\` sometimes.

@GreyCat:

> Ok, understood, I'll add normalization to `/` in file names then.

> Should be fixed now: https://github.com/kaitai-io/kaitai_struct_compiler/commit/2aef0de69fe3197e07ee1812f3e611162d6fc62e

I don't think this "normalization" was the best decision, either. I don't see any compelling reason why it should be done. Also, I'm not sure what it means to provide OS-independent paths - in general, paths are very much OS-dependent. You can achieve some degree of compatibility of relative paths, but not much more.

And the piece of code responsible for this "normalization" is very naive ([`ProblemCoords.scala:36-38`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/7071a9de11de3bafa711b6eb21961bbf7680623a/shared/src/main/scala/io/kaitai/struct/problems/ProblemCoords.scala#L36-L38)):

```scala
object ProblemCoords {
  def formatFileName(file: Option[String]): String = file match {
    case Some(x) => x.replace('\\', '/')
```

Unix paths use only forward slashes `/` to separate names, so nothing stops you from creating a file with name `hello\world.ksy` (not to be confused with a file `world.ksy` in subdirectory `hello` - that would be `hello/world.ksy`). However, this slash normalization code butchers it so that it's indistinguishable from a `world.ksy` in a `hello` subdir:

```console
$ ls -la
total 0
drwxrwxrwx 1 pp pp 4096 Aug 17 11:11  .
drwxrwxrwx 1 pp pp 4096 Aug 17 11:11  ..
-rwxrwxrwx 1 pp pp   68 Aug 17 11:11 'hello\world.ksy'

$ kaitai-struct-compiler -- --ksc-json-output -t ruby -d outdir ./hello\\world.ksy
{"./hello\\world.ksy": {"errors": [{"file": "./hello/world.ksy","path": ["meta","endian"],"message": "unable to parse endianness: `le`, `be` or calculated endianness map is expected"}]}}
                                                    ^

$ kaitai-struct-compiler -- -t ruby -d outdir ./hello\\world.ksy
./hello/world.ksy: /meta/endian:
       ^
	error: unable to parse endianness: `le`, `be` or calculated endianness map is expected

```

We could spend time tweaking it so it doesn't cause any problems, but as I said, I think the slash normalization is unnecessary. IMHO the compiler should treat the paths from the user as opaque strings and merely pass them to the underlying platform and all console/JSON outputs unchanged. If the accepted string matches some supported path format on the particular platform, great; if the path is invalid, the platform will report an error, which the compiler just passes along. In fact, there's no need for the compiler to worry about which path formats are supported on which platform.

**Comment by generalmimon** [comment]
I believe the proposed solution of "treating paths as opaque strings" is now fully implemented in KSC by commits https://github.com/kaitai-io/kaitai_struct_compiler/compare/7071a9de11de3bafa711b6eb21961bbf7680623a...2b84e0a1e29712304debf709c143d9505e3062ca.

The band-aid commit in `ksv` trying to add support for forward slash paths on Windows (https://github.com/kaitai-io/kaitai_struct_visualizer/commit/d9a3dbdc6c06ffd47c94e9f012802b0d61b68af9) was [reverted](https://github.com/kaitai-io/kaitai_struct_visualizer/commit/d0b2e4ef560868e555542fa4f014e6ec86768b53), since it's not needed anymore - KSC now preserves the original path "spelling" in JSON keys of `--ksc-json-output`, so `ksv` will get a 100% match simply by indexing the JSON object with the same path string passed that it passed to KSC (regardless of whether the user typed `./hello_world.ksy`, `.\hello_world.ksy` or `.///hello_world.ksy`).

This issue is therefore resolved.
