### ISSUE TITLE
Using NULL without quotes causes TypeError

### ISSUE THREAD

**Issue by moritonal** [kaitai-io/kaitai_struct#511]
Many binary formats refer off the cuff to 0x00 as "null" in various enum's and key names. When not quoted however the Javascript converter treats this as the null value rather than as a string. The issue can therefore be broken into two causes:

1. Null being treated as a value rather than as a string for id's and enum names.

2. The exception message being given back to the user is vague and doesn't help the developer solve the problem with quotes. Simply: "KS compilation error:  TypeError: Cannot convert undefined or null to object" with no line number.

Fixing either of these issues will solve the overall issue.

NP. Mandatory quotes for values is fine given it might allow expressions to be used later on, as long as corresponding examples of enum also use quotes to show they're evaluated.

**Comment by GreyCat** [comment]
No updates / complaints in more than 1 year, so I guess everyone's happy with proposed error reporting => closing this one.

**Comment by generalmimon** [comment]
In fact, the bug initially reported [in this issue](https://github.com/kaitai-io/kaitai_struct/issues/511#issue-399117665), i.e.:

> 2\. The exception message being given back to the user is vague and doesn't help the developer solve the problem with quotes. Simply: "KS compilation error:  TypeError: Cannot convert undefined or null to object" with no line number.

... still persisted in the Web IDE (more precisely, in the JavaScript build of KSC that it uses under the hood) until I fixed it a few days ago (on 2024-09-25) in https://github.com/kaitai-io/kaitai_struct_compiler/commit/8d913def37a571bf8dd817f4f0d0f3bab3751f3a. I explained the problem in detail in the [commit message](https://github.com/kaitai-io/kaitai_struct_compiler/commit/8d913def37a571bf8dd817f4f0d0f3bab3751f3a). I didn't know this issue existed, otherwise I would have linked to it from the commit message as well.

BTW, this compiler update was already deployed to https://ide.kaitai.io/devel/, so you can verify that it is now fixed, for instance using the same example that I gave in https://github.com/kaitai-io/kaitai_struct_compiler/commit/8d913def37a571bf8dd817f4f0d0f3bab3751f3a:

```ksy
meta:
  id: js_cannot_convert_null
instances:
  foo:
    # NOTE: the following line "value:" is equivalent to "value: null" in YAML
    value:
```

For comparison, you can also try this .ksy snippet at https://ide.kaitai.io/ (the stable deployment powered by KSC 0.10) to see what it looked like when it was _not_ fixed.

So let me briefly reopen this issue and then immediately close it to fix the "metadata" of this issue to reflect that it was in fact fixed only recently (not in 2019 or 2017).

**Comment by generalmimon** [comment]
Fixed in https://github.com/kaitai-io/kaitai_struct_compiler/commit/8d913def37a571bf8dd817f4f0d0f3bab3751f3a
