### ISSUE TITLE
Seek magic values on instances

### ISSUE THREAD

**Issue by AlexAltea** [kaitai-io/kaitai_struct#530]
## Background

I'm trying to describe some GPU bytecode blobs followed by some metadata. The bytecode itself is irrelevant, but the metadata itself is important for my use case. This metadata is a footer that describes said AMD GCN shaders generated by drivers/compilers that target AMD GPUs in PlayStation 4 hardware.

The hardware receives pointers to these blobs and starts executing instructions starting from said pointers until it reaches an `S_ENDPGM` instruction. Therefore, there are **no headers**. The only hint that a footer exists is the `OrbShdr` magic value. Even worse: This magic value appears in the *middle* of the footer.

In summary:
```
        bytecode                   metadata / footer
 _____________________ __________________________________________
+---------------------+------------------------------------------+
|         ...         |   ...   | "OrbShdr" | ... | length | ... |
+---------------------+------------------------------------------+
```

Additionally, there's a `length` field needed to determine how large the bytecode is. This is important since the first bytes of the metadata could be interpreted as valid AMD GCN bytecode. Therefore the first step in the parsing process is figuring out where the `OrbShdr` magic is.

---

In order to parse this, we need some way of seeking that magic value, I wasn't able to find any similar issues on GitHub, but I did find some comment from @GreyCat on the matter:
https://gitter.im/kaitai_struct/Lobby?at=5a6b952cce68c3bc740aafb5

Basically we could have something like:
```yml
instances:
  footer:
    seek: "OrbShdr"
    type: orbshdr_footer
```

The parser would actively search for the a magic byte sequence, and parses the rest of the format from there. Is this a reasonable feature request, or are there easier ways to implement this?

**Comment by KOLANICH** [comment]
#225

**Comment by dgelessus** [comment]
If multi-byte `terminator`s were supported (#158), they could also be used to implement this:

```yaml
seq:
  - id: data
    terminator: "OrbShdr"
  - id: footer
    type: footer
```

Then you also know the location of the magic signature (`data.length`) and can parse the data around it using instances.

**Comment by AlexAltea** [comment]
@dgelessus Good point, thank you! This looks like the best approach as it doesn't require introducing a new attribute. Plus, it allows to keep everything as a sequence (which it actually is!), rather than making an instance out of it.

Since #158 is clearly superior to my proposal I'll close this issue.

**Comment by KOLANICH** [comment]
>If multi-byte terminators were supported (#158), they could also be used to implement this:

Multi-byte terminators have the drawback of storing everything preceeding.

**Comment by dgelessus** [comment]
> Multi-byte terminators have the drawback of storing everything preceeding.

Good point, that could be an issue if there is a lot of data before the magic value. Perhaps there should be an attribute like `discard: true` to mark that a field should be read and parsed, but not kept in memory afterwards. (This could also be useful in other cases, for example if you have a fixed number of bytes that you know are junk.)

**Comment by KOLANICH** [comment]
>there should be an attribute like `discard: true`

I remember now that one can leave a field without an `id`, though the effect is not the same: the member is actually generated. Maybe this should be changed.

**Comment by webbnh** [comment]
>Multi-byte terminators have the drawback of storing everything preceeding.

That drawback comes from reading a variable-sized, terminated field -- it has little to do with the size of the terminator.  The challenge is that you have to read the field in chunks which are no bigger than the terminator and which are small enough that they cannot reach past the end of the terminator.

If, for example, the terminator is "OrbShdr", then you have to read the code in chunks of seven bytes or fewer.  If the end of the read matches the beginning of the terminator, then you have to read enough bytes to complete the match and see if it matches.  If it does match, then the read is complete (and you either include or omit the terminator from the read as required); otherwise, you again check if the end of the read matches the beginning of the terminator, and read the required number of bytes (up to, here, seven) to complete the terminator.

It's probably more efficient to do the read one byte at a time (depending on lower-level code to buffer the I/O) and to maintain a state machine which indicates when the match is complete.  However, if a partial match fails, then the state has to be replayed starting at each byte after the match which failed, which could be a performance pothole.  Nevertheless, in each case the effect is the same:  the read has to be done in small chunks and stopped only when the terminator matches.  In all cases, the bytes read have to be stored (at least until they are determined to match the terminator).

**Comment by KOLANICH** [comment]
>That drawback comes from reading a variable-sized, terminated field -- it has little to do with the size of the terminator.

Definitely. This is by design. It was just proposed to misuse the `terminator` field for the purpose it was not designed for.

>It's probably more efficient to do the read one byte at a time

definitely, and it was proposed in https://github.com/kaitai-io/kaitai_struct/issues/225#issuecomment-325024835

**Comment by webbnh** [comment]
> definitely

I think it's only "definitely" in the case where partial terminators don't frequently occur in the terminated data.  Otherwise, the code will spend a lot of time re-starting the state machine on each failed match.

I'm also concerned about another corner case:  it would be best if we avoided depending on the underlying stream being seekable.  Yes, we can plausibly assume that substreams created by KS can be seeked, but the main stream provided by the user might _not_ be seekable.  (Consider reading from a live network transfer.)  In that case, local buffering might allow seeking backwards a modest number of bytes, but if we happen to be looking at the beginning of a freshly-read buffer, then there is nowhere to seek backwards to.  And, it's possible that the terminated data field could be very large.  So, whatever the solution is, it would be best if the state were maintained in KS and not counting on being able to re-read it from the input.

**Comment by dgelessus** [comment]
> > That drawback comes from reading a variable-sized, terminated field -- it has little to do with the size of the terminator.
> 
> Definitely. This is by design. It was just proposed to misuse the `terminator` field for the purpose it was not designed for.

I disagree that this would be "misusing" the terminator field. Based on @AlexAltea's description it seems that a terminated string would describe that part of the format best: you have random data, followed by a known separator string, followed by a known structure - if you ask me, the first part sounds like a terminated string.

I'm not saying that the `seek` feature described here is completely unnecessary (there are probably formats that would require such a feature), but it's not needed for OP's format in particular.

**Comment by KOLANICH** [comment]
>but the main stream provided by the user might not be seekable.

Non-seekable streams are not supported by KS. It would break `pos` instances. 

>Based on @AlexAltea's description it seems that a terminated string would describe that part of the format best: you have random data, followed by a known separator string, followed by a known structure - if you ask me, the first part sounds like a terminated string.

I is a hack. It is not meant to work this way. A blob with a terminator and signature matching are different things.

Signature matching:
    - there may be other matches of signature, we need only valid ones
    - usually there is a window of offsetz, if a valid match is not found within a window, there is no match
    - no need to store the preceeding stuff

Blob termination:
    - will go till the end of file. If the file is of TiB size, it would be DoS.
    - will use the first match
    - stores the preceeding stuff
    

It is possible to use latter as a surrogate of former, but it is not a good surrogate.

**Comment by GreyCat** [comment]
Hey, this discussion actually clicked and generated a more generic idea for me, which I'd like to share in separate issue: #538. Could you take a look?
