### ISSUE TITLE
CI: trigger web IDE rebuild after publication of new compiler to npm

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#573]
Main CI pipeline now publishes [npm package with compiler](https://www.npmjs.com/package/kaitai-struct-compiler). It would be great if we could trigger automatic rebuild of https://ide.kaitai.io/devel/ every time a new compiler version is available.

**Comment by generalmimon** [comment]
## Motivation

This would be great, because it's embarrassing to explain everybody that "stable Web IDE is old, devel Web IDE is less old, but to use cutting edge features, you still have to set up a local environment". Most people already got used to it, that if they need some fresh features, they just can't use the Web IDE. It looks like we _unfortunately_ can't do anything with it (for example https://github.com/kaitai-io/kaitai_struct/issues/413#issuecomment-510507577), which is terrible, because we surely can.

I think this is the most important and most useful improvement at all and IMHO we should solve this before everything else. If we add some new feature or fix a bug, few people will notice. But if it was possible to use the latest features in Web IDE, I'm sure all people would appreciate it.

It would help me a lot when developing some complex format spec in the devel Web IDE, for example. I often decide to use some new feature which isn't available here yet. But I want to continue using the webide, because it's the most convenient developing tool for KSY specs. I solve it by repeatedly compiling the KSY locally by command-line `kaitai-struct-compiler` for JS with `--debug`, then switching the tab to _JS code (debug)_ in the Web IDE and replace all code with that generated locally. It works pretty well, but it's an unnecessary hassle.

## The solution

I hope this is quite straightforward to fix.

1. Fix `npm publish` of the compiler. @cherue has already fixed it, we just need to merge https://github.com/kaitai-io/kaitai_struct_compiler/pull/178. Could you please check it out, @GreyCat?

2. Trigger the rebuild of https://github.com/kaitai-io/kaitai_struct_webide repo after pushing to the main repository. The simplest solution is probably to make an empty commit in the kaitai_struct_webide repo every time we commit to kaitai_struct repo to trigger the Travis CI build. The problem with this is that soon we'll have a congested commit history. Better solution is to trigger the build via the [Travis CI API](https://docs.travis-ci.com/user/triggering-builds/). Maybe it's harder to work with it, but it's cleaner and we'll get a lot of options to tweak.

**Comment by GreyCat** [comment]
It's, unfortunately, not *very* straighforward.

> * Fix `npm publish` of the compiler. @cherue has already fixed it, we just need to merge [kaitai-io/kaitai_struct_compiler#178](https://github.com/kaitai-io/kaitai_struct_compiler/pull/178). Could you please check it out, @GreyCat?

Merged this fix, but the problem is actually deeper. We need a more stable and documented mechanism for versioning for WIP version number in between official releases. Nowadays, it's totally chaotic and depends on certain CI-specific features.

Hope that fix will at least make some progress towards *any* publication at all.

> * Trigger the rebuild of https://github.com/kaitai-io/kaitai_struct_webide repo after pushing to the main repository. The simplest solution is probably to make an empty commit in the kaitai_struct_webide repo every time we commit to kaitai_struct repo to trigger the Travis CI build. The problem with this is that soon we'll have a congested commit history. Better solution is to trigger the build via the [Travis CI API](https://docs.travis-ci.com/user/triggering-builds/). Maybe it's harder to work with it, but it's cleaner and we'll get a lot of options to tweak.

Triggering the build is actually relatively straightforward. It would be even more so with GitHub Actions builds.

**Comment by GreyCat** [comment]
Looks like it worked!

npm: [0.9.0-SNAPHSOT20200118.114828.0d77fe98](https://www.npmjs.com/package/kaitai-struct-compiler/v/0.9.0-SNAPHSOT20200118.114828.0d77fe98)

I probably need to fix the SNAPHSOT typo, though %)

**Comment by GreyCat** [comment]
Ok, much better: [0.9.0-SNAPSHOT20200118.151547.90382c3d](https://www.npmjs.com/package/kaitai-struct-compiler/v/0.9.0-SNAPSHOT20200118.151547.90382c3d). Thanks, @cherue!

I've triggered webide build manually: https://travis-ci.org/kaitai-io/kaitai_struct_webide/builds/638849775 — next step is getting some token/webhook and triggering them automatically.

I wonder if moving any of these moving parts to GH Actions will make it easier...

**Comment by generalmimon** [comment]
> I've triggered webide build manually

I checked it out. It revealed some problems:

1. The Web IDE doesn't get the latest compiler version available. The [travis.yml](https://github.com/kaitai-io/kaitai_struct_webide/blob/18d60f266b26ec4927a5a36b99283c222759d6d7/.travis.yml) looks like this:

```yaml
install:
  - pip install --user -r requirements.txt
  - npm install
  - 'if [[ "$TRAVIS_BRANCH" = stable ]]; then npm install kaitai-struct-compiler@latest && npm install kaitai-struct@latest && python vendor_build.py; fi'
```

The command `npm install` installs all packages listed in the package.json file, trying to satisfy the version constraints specified here. The following command overrides the version of the compiler and runtime to `@latest` for the branch `stable`. `@latest` means stable, so it's OK, it won't get the most recent version.

The version of `kaitai-struct-compiler` in [package.json](https://github.com/kaitai-io/kaitai_struct_webide/blob/18d60f266b26ec4927a5a36b99283c222759d6d7/package.json#L19) is  `"^0.8.0-SNAPSHOT.20180126.2450"` (it's the version used for the `master` branch). ` 0.9.0-SNAPSHOT...` doesn't satisfy this constraint due to semantic versioning (if the major version is 0, incrementing minor version is considered as a breaking change, otherwise it would work).

I would suggest version `@next` for the devel (or actually `master`) branch (it's possible to use `"next"` version in the package.json), because this is exactly what we need: the **most recent version available**. Something like `^0.9.XXX` will also work, we just must not forget to update it after releasing 0.9.

2. I tried the `kaitai-struct-compiler@next` version manually and it doesn't work due to renaming the generated JavaScript compiler code from `kaitai-struct-compiler.js` to `kaitai-struct-compiler-js.js`. It was introduced with the commit https://github.com/kaitai-io/kaitai_struct_compiler/commit/97ac8e4c3edf7b68e77d04579e82d7a6a94f5566#diff-fdc3abdfd754eeb24090dbd90aeec2ceR168. I don't know what this change should fix, but if we need to have the main script named `kaitai-struct-compiler-js.js`, it's neccessary to keep [this line](https://github.com/kaitai-io/kaitai_struct_compiler/blob/90382c3d0a3a5d08f9b154264d3510fe8714b424/js/package.json#L29) in sync, otherwise npm won't find it. If not, just remove the `"-js"` suffix from [this line](https://github.com/kaitai-io/kaitai_struct_compiler/blob/90382c3d0a3a5d08f9b154264d3510fe8714b424/build.sbt#L161).

**Comment by GreyCat** [comment]
WebIDE build came through, but, alas, no cigar.

Had to do some fixes to both how npm package is built + how webIDE picks newest (`next`) version of ksc for master branch — and, hurray, here we are: https://ide.kaitai.io/devel/

> Kaitai WebIDE version: 0.1-SNAPSHOT-7aa53ce (2020-01-18 20:28:13, license)
> Kaitai compiler version: 0.9-SNAPSHOT20200118.201657.b820529e (2020-01-18T20:16:57+00:00)

**Comment by GreyCat** [comment]
@generalmimon Apologies for missing your analysis, you're completely correct, and it turned out that I did exactly as you've suggested.

Next topic would be:

* debating is there any value in switching kaitai_struct / kaitai_struct_webide CI builds to GH Actions?
* actually triggering kaitai_struct_webide build from kaitai_struct ([Travis docs](https://docs.travis-ci.com/user/triggering-builds), [GH Actions docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#external-events-repository_dispatch))

**Comment by GreyCat** [comment]
Basically, Travis version of "trigger new build" boils down to:

* Get `kaitai_struct_webide` repo's Travis API token
* Put that token into secure env vars in `kaitai_struct`
* Run HTTP query using curl / wget whenever one wants to trigger a build

**Comment by GreyCat** [comment]
Ok, I've [implemented this for Travis](https://github.com/kaitai-io/kaitai_struct/commit/12783032ec04a42c3fc8e1fe8158e345eeecd6cf) for now.

Here's [`next` version at npmjs](https://www.npmjs.com/package/kaitai-struct-compiler/v/0.9.0-SNAPSHOT20200119.115739.6792b978) and here's [Travis build for kaitai_struct_webide](https://travis-ci.org/kaitai-io/kaitai_struct_webide/builds/639096536) which was auto-triggered and included it.
