### ISSUE TITLE
Format Gallery Databases Images missing

### ISSUE THREAD

**Issue by ogamespec** [kaitai-io/kaitai_struct#698]
Visualized image missing:

https://formats.kaitai.io/sqlite3/index.html

**Comment by ogamespec** [comment]
Same to http://formats.kaitai.io/bmp/index.html

**Comment by KOLANICH** [comment]
Thanks for reporting that!

<details>
<summary>offtop</summary>

@ogamespec, since your links contain `http:`, I guess you don't have `HTTPSEverywhere` addon installed or EASE enabled (it is pretty little sense to use it without EASE). I strongly recommend you to install it and enable EASE (this will assumme that all the websites support TLS and connect only via it, sites without TLS are rare these days and whether you really need them can be decided manually on per-site basis).

</details>

**Comment by GreyCat** [comment]
These are two different issues:

* for sqlite3 — it looks like a problem with the compiler not supporting something in ksy to emit the right graphviz diagram
* for bmp — it's the question of v0.9 compiler being required, and formats.kaitai.io infrastructure doesn't provide it yet

**Comment by ogamespec** [comment]
Still not fixed.

![image](https://github.com/user-attachments/assets/ab19fee8-73ee-47ff-a63b-48135f6b656f)

**Comment by generalmimon** [comment]
@ogamespec:

> Still not fixed.

Correct. [formats.kaitai.io](https://formats.kaitai.io/) uses the latest _stable_ compiler, which is KSC 0.10 at this point, where it is not fixed yet. However, the open/closed issue status refers to the most recent development version at https://github.com/kaitai-io/kaitai_struct_compiler/tree/master.

If you build https://github.com/kaitai-io/kaitai_struct_compiler/tree/3c855b38976df73e8b1500bf85aaad06287d2350 from source (see [instructions](https://doc.kaitai.io/serialization.html#_building_the_compiler_from_source), but checkout `3c855b38` instead of <code><del>serialization</del></code>), you'll find that it is fixed.
