### ISSUE TITLE
C# byte array `Count` instead of `Length`

### ISSUE THREAD

**Issue by kjczarne** [kaitai-io/kaitai_struct#715]
Hi,
First of all many thanks for creating this, `kaitaistruct` saves me a lot of trouble building parsers. Second of all, sorry if this is a mistake on my part as I'm completely new to C# but it seems to me that for some reason the compiler uses a wrong property to refer to the length of a byte array.

```csharp
public Entry Payload
        {
            get
            {
                if (f_payload)
                    return _payload;
                long _pos = m_io.Pos;
                m_io.Seek(12);
                __raw_payload = m_io.ReadBytes(PayloadRaw.Count);
                var io___raw_payload = new KaitaiStream(__raw_payload);
                _payload = new Entry (io___raw_payload, this, m_root);
                m_io.Seek(_pos);
                f_payload = true;
                return _payload;
            }
        }
```

In the above code `PayloadRaw` does not have an attribute `Count`. When replaced to `Length` however, everything seems to be working fine. I can confirm that the problem appears when building a .NET Core app as well as a standard .NET dll file. The field this pertains to is an `instances` field:

```yaml
instances:
  payload:
    type: entry
    pos: 12
    size: payload_raw.size
```

Is my thinking correct that this should be easily fixable by modifying `TranslatorSpec`, `CSharpCompiler` and `CSharpTranslator` within `kaitaistruct-compiler`?

**Comment by generalmimon** [comment]
@kjczarne Thanks for reporting this! The problem with C# until today was that it had broken CI build (here's our [CI (continuous integration) dashboard](https://ci.kaitai.io/)) for quite a long time (4 months), so we couldn't really track the progress. But thanks to this issue here, I've finally focused on the problem and managed to fix it.

Also made some quick fixes in both compiler and runtime. Now the support rating of C# [in the CI](https://ci.kaitai.io/) is 91.8%, which is quite good!

**Comment by kjczarne** [comment]
Splendid! I can confirm from my side, the issue is fixed. Thanks for getting back so quickly :)
