### ISSUE TITLE
Unexpected behavior of enums in JavaScript?

### ISSUE THREAD

**Issue by kjczarne** [kaitai-io/kaitai_struct#717]
Hey guys!
This time I have played with parsers compiled to JavaScript and my unit tests didn't pass. When I looked into it, I noticed that the Enums behave in a bit weird way.

Take this for instance:
```javascript
var SomePacket = (function() {
  SomePacket.VendorEnum = Object.freeze({
    A: 4,
    B: 8,
    C: 12,

    4: "A",
    8: "B",
    12: "C",
  });
//... skipping the rest as it's not relevant for the issue
});
```

When I have a sub-type that is being switched on the value of the enum, everything looks nice and sweet:
```javascript
SomeSubtype.prototype._read = function() {
      switch (this._parent.vendorId) {
      case SomePacket.VendorEnum.C:  // C from VendorEnum used as expected
        this._raw_vendorSpecific = this._io.readBytesFull();
        var _io__raw_vendorSpecific = new KaitaiStream(this._raw_vendorSpecific);
        this.vendorSpecific = new CStatus(_io__raw_vendorSpecific, this, null);
        break;
      default:
        this.vendorSpecific = this._io.readBytesFull();
        break;
      }
    }
```

But the `vendorId` property itself remains an integer and I would expect it to become "C" string in this case, as defined in the enum, similar to what happens in Python.
```javascript
SomePacket.prototype._read = function() {
    this.vendorId = this._io.readU1();  // <- this takes the int value and
                                        //    does not seem to be assigned the
                                        //    corresponding str from enum later :(
}
// Expected value of vendorId on SomePacket instance: "C"
// Actual value of vendorId on SomePacket instance: 12
```

So perhaps I'm getting something wrong and there are other design choices driving this behavior. If so, I'd love to find out more and maybe you have suggestions for a fairly good workaround. But then again this feels like a big discrepancy between the Python and JavaScript code. I like how it's handled in C#, where the value becomes a corresponding attribute from the associated enum type.

**Comment by generalmimon** [comment]
@kjczarne 
> But the `vendorId` property itself remains an integer and I would expect it to become "C" string in this case

OK, let it happen:

```javascript
SomePacket.prototype._read = function() {
    this.vendorId = SomePacket.VendorEnum[this._io.readU1()];
}
```

Now the `vendorId` is equal to `"C"` (assuming that `this._io.readU1()` returns `12`). What now? How would you use this property in your application code, for example in a `switch`? You can no longer compare this value with stuff like `SomePacket.VendorEnum.C`, because it returns `number` and the `vendorId` is `string`. I see two ugly options here: matching string literals and numeric keys of the enum:

```javascript
switch (this.vendorId) {
  case "A":
    break;
  case "B":
    break;
// ...
}
```

```javascript
switch (this.vendorId) {
  case SomePacket.VendorEnum[4]:
    break;
  case SomePacket.VendorEnum[8]:
    break;
// ...
}
```

The first option is more readable, but it disables all useful IDE features like code completion, jump to definition and so on, because it's just a plain string literal, without any link to the originating enum. The second example does contain reference to the enum, but using "enum" this way totally misses the main purpose of the enums' existence, i.e. working with human-readable identifiers instead of cryptic numbers. So as you can see, working with an enum value of type string in JavaScript is quite clumsy.

> But then again this feels like a big discrepancy between the Python and JavaScript code. I like how it's handled in C#, where the value becomes a corresponding attribute from the associated enum type.

Please take into account that JavaScript does not have any built-in `enum` type, and using the approach with the object mapping integers to strings is IMHO the closest equivalent. But I think it's actually very close how are enums handled in JavaScript and C#. The usage in a switch is exactly the same: you can write `switch (v) {case Animal.Dog: ... break;}` in both languages, which is very readable and convenient. And if you feel the urge of getting a human readable value of the integer enum value (e.g. for dumping to the screen) in JavaScript, you can always do `SomePacket.VendorEnum[4]` and you'll get the string identifier.

And I don't really understand what do you mean with this sentence:

> I like how it's handled in C#, _where the value becomes a corresponding attribute from the associated enum type._

Let's take a look:

```csharp
public enum Animal
{
    Cat = 0,
    Dog = 1,
    Horse = 4,
    Platypus = 5,
}
```

Well, I suppose you're talking about the C# enum declaration syntax beauty, but the approach that is done in JavaScript right now is essentially doing the same thing, so I don't really know what's your point. If you have some better solution for enums in JavaScript meeting all usage requirements, please share it.

**Comment by GreyCat** [comment]
This probably needs to be documented, ideally somewhere around https://doc.kaitai.io/lang_javascript.html, so it won't be a surprise that for JS (as Perl, PHP and some other languages), all enums are represented just as integers, and enum dictionaries are used solely as constants.

**Comment by kjczarne** [comment]
@generalmimon Thanks for a detailed and comprehensive response! What I meant about C# may have come from poor understanding of JS Object prototypes (until now) and you're right, I just wish accessing the enum would be nicer and maybe more informative at runtime. Guess I'll just need to use the enum every time I want a string value but that's not a dealbreaker.

Here are the unit tests in C# and Python:
```csharp
// In C#:
Assert.Equal(SomePacket.SomeField, Kaitai.SomePacket.SomeFieldEnum.General);
```
```python
# Python has an Enum class, like you mentioned
self.assertEqual(self.all_pcaps.some_packet.some_field.name, "general")
self.assertEqual(self.all_pcaps.some_packet.some_field.value, 0)
```
I guess creating a custom class to make it behave like Python is also a bit of a bad idea, I could see something like:
```javascript
// Could be handled like in Python?
it('should return true', ()=>{assert.equal(allPcaps.somePacket.someField.name, "general")})
it('should return true', ()=>{assert.equal(allPcaps.somePacket.someField.value, 0)})
```
But this may be too drastic of a change in behavior, and you probably had a good reason not to do it this way.

Anyways, I realized I can access my enums through Object protos and can check directly against them in the unit tests instead of having to use just integers, so I deem this issue resolved.

@GreyCat Yup, that was the first place I went to when I was like "huh? this isn't like it was in other runtimes" but didn't find anything about this behavior, that's why I opened up this issue to get some clarity.

Many thanks for your amazing work, prompt responses and great patience for novices!
