### ISSUE TITLE
Using Kaitai for 36 bits

### ISSUE THREAD

**Issue by StelluR** [kaitai-io/kaitai_struct#771]
So I know there is a size parameter that indicates how many bytes to read. The segment that I need to read is 36 bits long which is 4.5 bytes. I can't put this amount into the KSY file because it is not an integer.

I know i'm able to read bits via type: b5 for 5 bits but this variable can only go up to 32, thus 36 is out of that range.

How can I read 36 bits?

**Comment by KOLANICH** [comment]
You can dompose a struct of multiple variables

**Comment by generalmimon** [comment]
> I know i'm able to read bits via type: b5 for 5 bits but this variable can only go up to 32, thus 36 is out of that range.

It depends on the target language. AFAIK in most languages you can go up to 64 bits without losing precision, because they return 64-bit integers (if you want more, you either get an exception, or the leftover bits are silently discarded - the `long` type overflows). The only language which has 32 bits as the limit is [JavaScript](https://github.com/kaitai-io/kaitai_struct_javascript_runtime/blob/1fd3006373547792589310bc0746556bb17a697e/KaitaiStream.js#L420-L423), because all bitwise operators in JS automatically convert their operands to 32-bit integers (from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Signed_32-bit_integers)):

> The operands of all bitwise operators are converted to signed 32-bit integers in [two's complement](https://en.wikipedia.org/wiki/Two%27s_complement) format, except for zero-fill right shift which results in an unsigned 32-bit integer.

So until we use use some `bigInt` library (e.g. [`big-integer` from npm](https://www.npmjs.com/package/big-integer), but there are many others, see https://github.com/kaitai-io/kaitai_struct/issues/183#issuecomment-307553508) which provides a way to represent numbers larger than **2<sup>53</sup> - 1** (the native [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) by itself is not an option, it has been added relatively recently, and it has quite lousy support in browsers: see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Browser_compatibility) and [caniuse](https://caniuse.com/#feat=bigint)), if we removed the limitation to 32 bits now, the `readBitsInt` methods would silently discard all bits over 32 bits. See https://github.com/kaitai-io/kaitai_struct/issues/183.

@StelluR So yeah, as @KOLANICH suggest, if you are using JavaScript, your best bet is to split the 36-bit number into multiple fields, and then compose them in your application code.
