### ISSUE TITLE
"<>" in expression language occasionally not allowed?

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#777]
I don't know how things implemented in fastparse, but wouldn't this code never match `<>` ?
https://github.com/kaitai-io/kaitai_struct_compiler/blob/0f32f3734dad0039dffb2275d38612eb779689ec/shared/src/main/scala/io/kaitai/struct/exprlang/Expressions.scala#L60-L69

In simplified form:
```js
comp_op
  = "<="
  / ">="
  / "=="
  / ">"
  / "<" // if this matched...
  / "<>"// ...that can't be matched
  / "!="
  ;
```

In PEG choice is ordered, so when `<` matched, `<>` won't be even tried

**Comment by dgelessus** [comment]
Personally I would vote for dropping the `<>` operator completely. As far as I can tell it's completely equivalent to `!=`, which is the more common spelling. I don't think there's any use in having two spellings for the same operator.

As far as I can tell, @Mingun is right - the parser doesn't accept the `<>` operator (I tested both the standalone JVM parser and in the WebIDE).

```
/seq/0: parsing expression 'true <> true' failed on 1:6, expected "or" | CharsWhile(Set( , n)) | "\\\n" | End
```

Since it's already broken, I don't think it many people will miss the `<>` operator if it is removed :)

**Comment by Mingun** [comment]
I also think, that `!=` looks better

**Comment by GreyCat** [comment]
Totally agree. As you might have seen in headers of Expressions.scala — it was more or less borrowed as is from sample of Python parser in FastParse, so it brought most of the Python-like syntax. I agree that I've never ever seen `<>` in the wild in Python code, and it probably explains why FastParse implementation of it might have been broken from the start. Let's get rid of it for clarity.

**Comment by dgelessus** [comment]
> I agree that I've never ever seen `<>` in the wild in Python code

Probably because it's been [removed since Python 3.0](https://docs.python.org/3/whatsnew/3.0.html#removed-syntax) in favor of `!=`. :)
