### ISSUE TITLE
Python: 000010 (bytes) represented as 12 (int)

### ISSUE THREAD

**Issue by angulartist** [kaitai-io/kaitai_struct#795]
I'm getting some weird behaviour (or I missed something) using the python compiler:

I have this bytes string: 

`b'000010001110110111101101001101000101110111001110110111101101001101001000110110000000000111000000000001000001000100001101000000110001000010100000000000000000000000000000000000000000000000000000000000000000000000000000000010011111010000000000100000000000010100000000000100111110000000010011111010000000000010000000010011111000000000000000'`

I'd like to decode the first 6 bits:

000010

**.read_bits_int(6)** should output **2** but I'm getting **12** instead...

Here is the code snippet I'm using:

```
source = io.BytesIO(b'000'.....)

stream = KaitaiStream(source)

print(stream.read_bytes(6), '--->', stream.read_bits_int(6))

# b'000010' ---> 12

```

By the way, in my ksy config this sequence fragment is identified as:

```
seq:
    - id: alpha
        type: b6
```

I really don't understand the behaviour, also read_bytes is a bit confusing at it takes a number of bits and not a number of bytes.

**Comment by dgelessus** [comment]
I think the problem is with how you're inputting the binary data into the parser. When you write 0s and 1s in a `b"..."` literal in Python, they are not interpreted as bits, but as the ASCII characters `0` and `1`. For example, when you write `b"00101010"`, you get a `bytes` object containing 8 bytes with the values 48 and 49 (the ASCII codes for the characters `0` and `1`):

```python
>>> list(b"00101010")                                                                                                                                                          
[48, 48, 49, 48, 49, 48, 49, 48]
```

When you pass data in that format into a KS parser, it doesn't parse the bits that you've written down, but the ASCII values of those bits. This means that when you give KS the data `b"00001000"` and ask it to parse the first 6 bits, it takes the ASCII value of the character `0` (which is 00110000 in binary), and reads the first 6 bits of *that* - which are 001100 in binary, or 12 in decimal.

The fix here would be to first convert the string of `0` and `1` characters into a byte array. Something like this should work:

```python
>>> bitstring = '000010001110110111101101001101000101110111001110110111101101001101001000110110000000000111000000000001000001000100001101000000110001000010100000000000000000000000000000000000000000000000000000000000000000000000000000000010011111010000000000100000000000010100000000000100111110000000010011111010000000000010000000010011111000000000000000'
>>> data = bytearray()
>>> for i in range(0, len(bitstring), 8): # iterate over groups of 8 bits
...     group = bitstring[i:i+8]
...     byte = int(group, 2)
...     data.append(byte)
... 
>>> data
bytearray(b'\x08\xed\xed4]\xce\xde\xd3H\xd8\x01\xc0\x04\x11\r\x03\x10\xa0\x00\x00\x00\x00\x00\x00\x00\x00\x00\t\xf4\x00\x80\x05\x00\x13\xe0\x13\xe8\x00\x80O\x80\x00')
>>> # now pass it into the KS parser
>>> import kaitaistruct
>>> import io
>>> source = io.BytesIO(data)
>>> stream = kaitaistruct.KaitaiStream(source)
>>> stream.read_bits_int(6)
2
```

**Comment by angulartist** [comment]
Thank you very much for the explanation
yup my input wasn't valid! :octocat:
