### ISSUE TITLE
XOR processing with multiple bytes

### ISSUE THREAD

**Issue by mnakamura1337** [kaitai-io/kaitai_struct#8]
Okay, I give up and start to file my requests properly, as you've requested ;)

So, I'd love to have XOR processing for a byte arrays or user subtypes with multiple bytes. That is, for example, given source bytes `src` and XOR argument `arg[0..2]` I'd like to have the following as a result:

```
[src[0] ^ arg[0], src[1] ^ arg[1], src[2] ^ arg[2],
 src[3] ^ arg[0], src[4] ^ arg[1], src[5] ^ arg[2],
 src[6] ^ arg[0], ...
```

Suggested syntax: `process: xor([0x11, 0x22, 0x33, ...])`.

Ideally, it will be a blessing if it would also work with byte arrays (i.e. keys) extracted as some other field, i.e.

```
- id: key
  size: 4
- id: encrypted
  process: xor(key)
```

**Comment by GreyCat** [comment]
Um, ok, I'm on that. The main problem here is that `[0x11, 0x22, 0x33]` you're proposing is *not* a byte array (as in `byte[]` in Java), but array of integers, that will be `ArrayList<Integer>` in Java. We need to somehow convert one into another.

**Comment by GreyCat** [comment]
Well, it's more or less done, at least for Ruby that you were most interested in: see http://kaitai.io/ci

The syntax is just as you've requested, but note that there's a crazy catch here: argument must be "byte array", not just any "array of integers". And here's the subtle difference:

* `[0x11, 0x22, 0x33]` is treated as byte array now
* `[0x11, 0x222, 0x33]` would be treated as array of integers, because of 0x222, which does not fit 1 byte and thus is represented by "generic integer" (i.e. `CalcIntType`) and not 1-byte type (`Int1Type`)
* `[0x11, 0x222 - 0x200, 0x33]` would be treated as array of integers too, despite 0x222 - 0x200 being able to fit in one byte, calculations would keep types promoted to `CalcIntType`.

**Comment by mnakamura1337** [comment]
Thanks, testing now.
Works like a charm!
I believe that you'd want to close this issue yourself, after adding support to all other languages?

**Comment by GreyCat** [comment]
Yeah. It's fully done now - http://kaitai.io/ci - except for 2 WIP languages, C# and Swift.
