### ISSUE TITLE
Check that Float is not NaN

### ISSUE THREAD

**Issue by kadhaus** [kaitai-io/kaitai_struct#805]
In my bytestring i have the subsequence "F1FFFFFF" (little endian). I need to recognize it as Float. But as you can see it's NaN. How can i check this? In other case that might be usual float number, and i need to check that number is not NaN.

**Comment by generalmimon** [comment]
https://github.com/kaitai-io/kaitai_struct_tests/pull/54 is related.

> But as you can see it's NaN. How can i check this?

KSY doesn't support NaN by itself (most likely it doesn't make much sense anyway), so you can work directly on the byte representation in the KSY (i.e. do several byte comparisons), or use some workaround in the target language you're interested in. What I have in mind is that in JavaScript, `NaN` is the only value that is unequal to itself, so a simple comparison `a != a` will tell you if `a` is `NaN`.

Sadly I don't know how `NaN` is represented and behaves in other languages, but I suggest investigating that in your language as well.  In fact, I hope that the implication `a != a` => `a` is `NaN` will apply also in other languages than JavaScript, because this behavior is supposedly enforced by the IEEE 754 spec ([Wikipedia](https://en.wikipedia.org/wiki/NaN#Comparison_with_NaN)):

> A comparison with a NaN always returns an _unordered result_ even when comparing with itself. (...) The equality and inequality predicates are non-signaling **so _x = x_ returning false can be used to test if _x_ is a quiet NaN**. (...)
>
> **Comparison between NaN and any floating-point value x (including NaN and ±∞)**
> Comparison | (...) | NaN ≠ x
> -- | -- | --
> **Result** | (...) | Always **True**

**Comment by kadhaus** [comment]
Ok, thank you for answer.
