### ISSUE TITLE
Please open Issues tab on kaitai-io/kaitai-io.github.io repo

### ISSUE THREAD

**Issue by JohnVeness** [kaitai-io/kaitai_struct#818]
Although I can open PRs on https://github.com/kaitai-io/kaitai-io.github.io, it would be useful to be able to create Issues too. Would that be possible? Apologies for asking here.

**Comment by generalmimon** [comment]
@JohnVeness I believe this repo (`kaitai_struct`) _is_ the _correct_ place to file issues for the [kaitai.io](https://kaitai.io/) homepage (and for all other components that don't have _Issues_ enabled). @GreyCat justified this [on Twitter](https://twitter.com/kaitai_io/status/1180644962674888704) a year ago:

> Yes, please use the main project's tracker — the reason for that is that until a very recent time GitHub had huge problems coordinating transfers between multiple projects, so we opted to have them all in one place — otherwise people frequently misplaced them.

So feel free to file any issues at https://github.com/kaitai-io/kaitai_struct/issues/new.

**Comment by generalmimon** [comment]
But maybe we can reconsider that, I'm not sure.

**Comment by JohnVeness** [comment]
Ah thanks, I see. I can understand the annoyance of misfiled issues. I believe GH does now allow issues to be transferred by repo owners, although I've never used it so don't know if there are any gotchas.

For me, it just feels wrong to file an issue in a repo that doesn't contain the code in question, but of course I would accept your decision!

**Comment by generalmimon** [comment]
> For me, it just feels wrong to file an issue in a repo that doesn't contain the code in question, but of course I would accept your decision!

You're right, and I actually feel the same way 😃

Probably the reason why this had been done has disappeared, so I'll allow that now and see what happens.

I was just a little worried that https://github.com/kaitai-io/kaitai-io.github.io is the _main repo_ even for unrelated issues with the kaitai.io site, but that is probably an unjustified concern.

**Comment by generalmimon** [comment]
You can now file the [kaitai.io](https://kaitai.io/) issues here: **https://github.com/kaitai-io/kaitai-io.github.io/issues**

Closing this ticket then.

**Comment by KOLANICH** [comment]
Should all the issues related to the website be transferred there?

**Comment by generalmimon** [comment]
> Should all the issues related to the website be transferred there?

Yes, any chance you would make a list for me?

**Comment by KOLANICH** [comment]
https://github.com/kaitai-io/kaitai_struct/issues/385
https://github.com/kaitai-io/kaitai_struct/issues/384
https://github.com/kaitai-io/kaitai_struct/issues/809
https://github.com/kaitai-io/kaitai_struct/issues/105

**Comment by generalmimon** [comment]
> * [ ]  #385
> * [ ]  #384
> * [ ]  #809

I don't think these should be transferred, because they do not relate exclusively to the https://kaitai.io/ site, but also to the other sites under the `*.kaitai` domain ([`doc.*`](https://doc.kaitai.io/), [`ci.*`](https://ci.kaitai.io/), [`formats.*`](https://formats.kaitai.io/) and [`ide.*`](https://ide.kaitai.io/)). These sites have actually nothing in common with the code in the https://github.com/kaitai-io/kaitai-io.github.io repository.

Seems I was right with this after all:

> I was just a little worried that people would think that https://github.com/kaitai-io/kaitai-io.github.io is the _main repo_ even for unrelated issues with the kaitai.io site, (...)

Because the homepage is deployed on the apex domain `kaitai.io`, it really might look like it's a central repo for all `*.kaitai.io` stuff, but that's not the case.

@JohnVeness 

> For me, it just feels wrong to file an issue in a repo that doesn't contain the code in question, but of course I would accept your decision!

Yeah, I understand it, but this is just how the current `kaitai-io` structure of repositories works. The structure and purpose of each repository is quite difficult to understand for the newcomers (for example, a very few people actually understand the concept of the "umbrella" repo [`kaitai_struct`](https://github.com/kaitai-io/kaitai_struct)), and thus it's probably better to limit the choice of where to file an issue to make the decision easier for the contributors.
