### ISSUE TITLE
Project tree still contains some 0.7-SNAPSHOT/0.8-SNAPSHOT/0.9-SNAPSHOT strings

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#828]
Just search for the "-SNAPSHOT" in the project root and you find this:
- https://github.com/kaitai-io/kaitai_struct_compiler/blob/6809f29e1d62ff8aa3036ec23093fdf0515dcd96/js/package.json#L38
- https://github.com/kaitai-io/kaitai_struct_compiler/blob/6809f29e1d62ff8aa3036ec23093fdf0515dcd96/jvm/src/main/scala/io/kaitai/struct/JavaMain.scala#L192-L207
- https://github.com/kaitai-io/kaitai_struct_tests/blob/0a5935def4af6615b6d7e60c75ea229eca8bec0c/translator/build.sbt#L3-L11

**Comment by generalmimon** [comment]
Good catch! It's not super critical, the `version` in [**kaitai_struct_compiler** / js/package.json:38](https://github.com/kaitai-io/kaitai_struct_compiler/blob/6809f29e1d62ff8aa3036ec23093fdf0515dcd96/js/package.json#L38) is not used (it's always overridden before publishing) and [**kaitai_struct_compiler** / .../JavaMain.scala:192-207](https://github.com/kaitai-io/kaitai_struct_compiler/blob/6809f29e1d62ff8aa3036ec23093fdf0515dcd96/jvm/src/main/scala/io/kaitai/struct/JavaMain.scala#L192-L207) only contains comments, but sure, let's fix it.

[**kaitai_struct_tests** / translator/build.sbt:3-11](https://github.com/kaitai-io/kaitai_struct_tests/blob/0a5935def4af6615b6d7e60c75ea229eca8bec0c/translator/build.sbt#L3-L11) is the most important one, because it may fetch old version from the local `~/.ivy2/local/io.kaitai/kaitai-struct-compiler_2.12` repository after `sbt publishLocal` of the local compiler version - that's definitely worth fixing, so that the KST translator uses the most recent compiler.

**Comment by generalmimon** [comment]
https://github.com/kaitai-io/kaitai_struct_tests/commit/23044601533c0e95fdc915c8f1f3667709d20fbe - updates the `0.9-SNAPSHOT` occurences in [**kaitai_struct_tests** / translator/build.sbt:3-11](https://github.com/kaitai-io/kaitai_struct_tests/blob/0a5935def4af6615b6d7e60c75ea229eca8bec0c/translator/build.sbt#L3-L11)
