### ISSUE TITLE
Allow a different endianness on the "contents" key of an attribute

### ISSUE THREAD

**Issue by 0x2b3bfa0** [kaitai-io/kaitai_struct#83]
I think that would be interesting to have the ability of specifying the endianness in a `contents` sentence...

Example: I have a little-endian file with this magic: `[0x13, 0x37, 0xbe, 0xef]`. Normally I would do this:

```yaml
- id: magic
  contents: [0xef, 0xbe, 0x37, 0x13]
```

However, it makes the magic loose the original meaning and results hard to read.

What about doing something like this (implementation idea by @GreyCat)?

```yaml
- id: magic
  contents: [0x13, 0x37, 0xbe, 0xef]
  contents-reverse: true
```

**Comment by crushedice2000** [comment]
I have a new implementation idea (maybe the most intuitive one). What about making the `content` key "flexible". This would mean that it would act like now in normal conditions, but it would accept `type`, `encoding` and so on:

Typical use: 

    - id: magic
      contents: [0xef, 0xbe, 0x37, 0x13]

"Advanced" use examples:

    - id: magic
      type: u4le # Stands for unsigned, 4 byte, little-endian. Maybe is not implemented or has another syntax.
      contents: 0x1337beef

    - id: magic
      type: reverse-string
      contents: 'FIG'

    - id: magic
      type: reverse-string
      contents: [0xbe, 0xef, 0xff, 0xf0, 0x0d]

**Comment by koczkatamas** [comment]
Yep, I was thinking a solution something like this.

The only thing I still don't like is the `reverse-string` type, if we want to implement this feature (instead of using `doc` property) then using `contents-reverse: true` is better IMHO, because `type` is a parsing primitive while the `contents` is a different mechanism full.

Also: I think this feature could be merged with the `check` / `guard` feature, where you specify the content type, the runtime reads it as a normal field and then checks equality.

If we go this way then it would be good if we'd made this feature thinking about serialization too in mind, so maybe `check` should accept single values and expressions too (so in this case we would use `check: 0xbaadbeef` instead of `check: '_ == 0xbaadbeef'`) or we could simply keep `contents` for this check-for-a-single-value case. So at serialization we can simply just write out this fix value.

**Comment by crushedice2000** [comment]
@koczkatamas: (From my total ignorance on the kaitai internals...)

What keeps the user form using `type`on an id that uses `contents`? Maybe could we add a `type: literal` by default for the `contents` sentence?

**Comment by koczkatamas** [comment]
Yeah it's just a technicality, the current implementation does not use `type` field if it finds a `contents` field. And if you use the `contents` field the two valid values for `type` would be `literal` and `reverse-string` while if you don't use `contents` it could be every type. 

This means that the `type` field would be used for two different purposes and this could cause misunderstandings IMHO.

**Comment by generalmimon** [comment]
Since the shipping of  https://github.com/kaitai-io/kaitai_struct/issues/435, I think the `valid` key can handle all the situations described here.

```yaml
meta:
  id: contents_reverse
  endian: le
seq:
  - id: byte_magic
    type: u4
    valid: 0x13_37_be_ef # affected by endianess
  - id: str_magic
    type: str
    encoding: utf-8
    valid: ('GIF').reverse
```

There's no need for `reverse-string`, `contents-reverse` or something similar, it brings only duplicity into the KS language. I also think that bytes specified in `contents` are expected to be present in the exact same order and it's weird to change this behavior. If some format's magic contents' order is switchable (and I believe that such exist), then ordinary `type: u4` with `valid` should be used.

You could argue that `contents` have essentially no size limit, while the largest integer type is `type: u8`. I've never seen a format which use switchable order of a bigger signature than 8 bytes (if you have, please share it), so I would not consider this a problem.

What do you think, @koczkatamas and @GreyCat?
