### ISSUE TITLE
Explicit output file for the compiler

### ISSUE THREAD

**Issue by abitrolly** [kaitai-io/kaitai_struct#853]
For my build scripts I need to track Python file produced by compiler. Unfortunately, the name of the output file depends on .ksy file content. Could there be an option like `-o, --output` to specify it?

**Comment by KOLANICH** [comment]
1. It would require changes in code generation. It generates multiple files: for each KSY file a file with python code. For C++ it generates a pair of files for each file. Just concatinating them and outputting into stdout makes no sense.
2. My JVM backend for kaitaiStructCompile.py gets results in memory without outputting them to disk. But there is an issue, the compiler is under GPL. I won't publish `kaitaiStructCompile.backends.JVM` until #466 is resolved.
3. Also #466 contains a proposal how to resolve this issue for `kaitaiStructCompile.backends.CLI` - outputting a zip archive into stdout.

If you get in-memory results for python, you can parse them with `ast.parse`, then merge into a one module by doing a topological sort on imports and replacing them with files contents + do renamings, if `import ... as ...` was used, then you can serialize the AST into source back with `astor`.

**Comment by abitrolly** [comment]
If it generates multiple files, then `--output` makes little sense. In that case the only way I see is to generate unique temporary directory and scan for first .py file with it. Luckily Python backend generates a single file output.

I also figured out that `--ksc-json-output` generates info about files being produced. This requires parsing JSON, and for error handling as well (#854), but may also solve the problem.

**Comment by KOLANICH** [comment]
>I also figured out that --ksc-json-output generates info about files being produced. This requires parsing JSON, and for error handling as well (#854), but may also solve the problem.

CLI backend is already parsing JSON:

https://github.com/kaitaiStructCompile/kaitaiStructCompile.backend.CLI/blob/ede351d51d8fa44ad78f721a05ab08cd7202290b/kaitaiStructCompile/backend/cmdline.py#L164

**Comment by abitrolly** [comment]
That's helps. Maybe it even returns the result that I needed. My IDE failed to gave any useful info about the declared return type.

**Comment by abitrolly** [comment]
While compiling 'squashfs.ksy', the result of CLI backend `compile()` returns this.

    {'squashfs_superblock': InFileCompileResult<PosixPath('/tmp/tmpmtb17tc2/squashfs_superblock.py')>}

I would prefer it will be easier to map input to output by using initial params as keys.

**Comment by KOLANICH** [comment]
What do you mean? Do you mean including a tuple of arguments to `compile`?

Currently the keys in this `dict` [are tied to the way KS identifies them internally, which is `meta.id`](https://github.com/kaitaiStructCompile/kaitaiStructCompile.backend.CLI/blob/ede351d51d8fa44ad78f721a05ab08cd7202290b/kaitaiStructCompile/backend/cmdline.py#L185L187) because of 2 reasons:

1. kaitaiStructCompile.py is not limited to python. It can be used to compile code for other target languages too. I just currently have never needed to use it this way, but I can imagine tools written in python that would need that.
2. it is the `meta.id` that is mapped to output file name, jot input file name. So, compiling 2 specs with the same id would just produce 1 output file.

The result is not  source code generated, but an object is because:
1. we need to have its metadata (`moduleName` and `mainClassName`) in order to properly use the generated code and the most correct way is to get them from the compiler itself.
2. there are different uses with different requirements. Some are OK with generating a file right on disk in the needed place, another ones need the source code in memory, and it is very undesireable to write to nonvolatile storage in this case because nonvolatile storage kay wear (mostly flash memory) and is slow (yes, I know, caching can reduce latencies, but still will have context switching penalty).

**Comment by abitrolly** [comment]
I mean that I want to compile a .ksy file, and I want the most simple way to get the result of compilation for that file by a simple lookup. Lookup instead of iterating over results to find out which result is about my file.

Even for iteration over result, the representation of that Result object when printed still bears no relationship to the `.ksy` or properties available.
