### ISSUE TITLE
splitting an array of bytes

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct#870]
I currently am looking at a specification, where there is a blob of bytes at some offset that consists of NUL terminated strings, but unsure how to process that. I couldn't find it in the user guide or documentation. What is the recommended way?

Currently I have something like this:

```ksy
instances:
  strings_block:
    pos: strings_block_offset
    size: size_dt_strings
    type: strings
    repeat: eos

types:
  strings:
    seq:
      - id: string
        type: strz
        encoding: ASCII
```

but that only gives me the first string.

**Comment by generalmimon** [comment]
The problem is that the `size` applies to every single element of the array separately, not on the entire array at once. See the User Guide section [8.4. Keys relating to the whole array and to each element in repeated attributes](https://doc.kaitai.io/user_guide.html#keys-repeated). In order to get `size_dt_strings` apply to the whole array, you must not use it directly on a repeated field, but just on a singular one containing a subtype with all the elements inside:

```diff
 instances:
   strings_block:
     pos: strings_block_offset
     size: size_dt_strings
     type: strings
-    repeat: eos
 
 types:
   strings:
     seq:
-      - id: string
+      - id: strings
         type: strz
         encoding: ASCII
+        repeat: eos
```

That should do.

**Comment by armijnhemel** [comment]
That works, thanks!
