### ISSUE TITLE
Building with 0.10 - #error "Incompatible Kaitai Struct C++/STL API: version 0.9 or later is required"

### ISSUE THREAD

**Issue by kovar-ursa** [kaitai-io/kaitai_struct#885]
Good morning,

We've been using kaitai-struct-compiler 0.9 successfully for quite a long time (and thank you all very much for it!)

I changed our Docker build process to pull from dl.cloudsmith.io successfully but can only find V 0.10 there. Building with it results in these errors:

#19 20.94  #error "Incompatible Kaitai Struct C++/STL API: version 0.9 or later is required"

If I build everything natively then I pull the compiler using brew and I get version 0.9:

`==> Pouring kaitai-struct-compiler--0.9.big_sur.bottle.tar.gz`

Is it possible to get v0.9 from dl.cloudsmith.io?

Thank you.

**Comment by generalmimon** [comment]
> I changed our Docker build process to pull from dl.cloudsmith.io successfully but can only find V 0.10 there.

> Is it possible to get v0.9 from dl.cloudsmith.io?

There are **two** repositories in Cloudsmith (https://cloudsmith.io/~kaitai/repos/): [_debian_](https://cloudsmith.io/~kaitai/repos/debian/packages/) and [_debian_unstable_](https://cloudsmith.io/~kaitai/repos/debian-unstable/packages/). If you want the stable release 0.9, that's the [**debian**](https://cloudsmith.io/~kaitai/repos/debian/packages/) repo, [_debian_unstable_](https://cloudsmith.io/~kaitai/repos/debian-unstable/packages/) is for latest development (unstable) builds pushed by a CI job. It's up to you what you choose, **unstable** usually have some additional features and bugfixes, but something might not work in a few consecutive versions until we fix it.

> #19 20.94 #error "Incompatible Kaitai Struct C++/STL API: version 0.9 or later is required"

This means that *you have* a 0.9+ compiler (it is a check in the **generated** code produced by KSC 0.9), but you're using an old version of the [Kaitai Struct C++/STL runtime library](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime). So you have to update the runtime library to proceed.

If you decide to use the stable KSC 0.9, get [C++/STL library with the tag `0.9`](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/tree/0.9), otherwise choose the latest commit on `master` to use with the latest unstable compiler.

**Comment by kovar-ursa** [comment]
Greetings,
Thank you for the very detailed and helpful reply.
-David
