### ISSUE TITLE
Passing `_index` into `params` with `enum` tag

### ISSUE THREAD

**Issue by cso-idn-player** [kaitai-io/kaitai_struct#975]
I'm having issue to passing `_index` value into a param linked by an enum.

Sample .ksy script:
https://gist.github.com/cso-idn-player/347e9e6c68fd356d446ea804706e913d

KSC version 0.9 (downloaded from official website):
```
D:\PortablePrograms\kaitai_struct_compiler\0.9\bin>ksc --version
kaitai-struct-compiler 0.9

D:\PortablePrograms\kaitai_struct_compiler\0.9\bin>ksc -d ..\..\__workroom -t python ..\..\__workroom\goldsource_engine_bsp.ksy
/seq/1/type: can't pass argument #0 of type CalcIntType into parameter `type` of type EnumType(List(lump_type),IntMultiType(true,Width4,None))
```

KSC version 0.10-SNAPSHOT-0a3dcbfb (built manually #974):
```
D:\PortablePrograms\kaitai_struct_compiler\0.10-SNAPSHOT\bin>ksc --version
kaitai-struct-compiler 0.10-SNAPSHOT

D:\PortablePrograms\kaitai_struct_compiler\0.10-SNAPSHOT\bin>ksc -d ..\..\__workroom -t python ..\..\__workroom\goldsource_engine_bsp.ksy
../../__workroom/goldsource_engine_bsp.ksy: /seq/1/type: error: can't pass argument #0 of type CalcIntType into parameter `type` of type EnumType(List(lump_type),IntMultiType(true,Width4,None))
../../__workroom/goldsource_engine_bsp.ksy: /types/lump_leafs/types/leaf/seq/6/type: error: can't pass argument #0 of type CalcIntType into parameter `type` of type EnumType(List(ambient_type),IntMultiType(true,Width4,None))
```

But, successfully parsed via Kaitai Web IDE devel:
```
Kaitai WebIDE version: 0.1-SNAPSHOT-[b75f16d](https://github.com/kaitai-io/kaitai_struct_webide/commit/b75f16dd079ca7f779eb12c565569591ae2a1bfc) (2022-03-13 21:05:17, [license](https://raw.githubusercontent.com/kaitai-io/kaitai_struct_webide/master/LICENSE))
Kaitai compiler version: 0.10-SNAPSHOT20220312.201918.860afd0c (2022-03-12T20:19:18+00:00)
```

**Comment by cso-idn-player** [comment]
Sample binary file, if necessary:
https://filebin.net/hiakfjus3nbxfnfw/test.bsp

**Comment by generalmimon** [comment]
> I'm having issue to passing `_index` value into a param linked by an enum.

That's expected. Kaitai Struct language is strongly typed: integer type and enum type are considered distinct, and they're incompatible (see https://doc.kaitai.io/user_guide.html#_conditionals). They're not implicitly converted between each other, but you can convert them explicitly:

- From enum value to integer:
  ```ksy
  instances:
    enum_val:
      value: animal::horse
    int_val:
      value: enum_val.to_i
  enums:
    animal:
      5: horse
  ```
  
  See https://doc.kaitai.io/user_guide.html#_enums:
  
  Method name | Return type | Description
  -- | -- | --
  `to_i` | Integer | Converts an enum into the corresponding integer representation

- From integer to enum value:
  ```ksy
  instances:
    int_val:
      value: 5
    enum_val:
      value: int_val
      enum: animal
  enums:
    animal:
      5: horse
  ```

  Just note that due to a compiler bug (https://github.com/kaitai-io/kaitai_struct/issues/694), the `value` expression here sadly isn't checked by KSC, so double-check if it is valid (the bug causes that you can even reference non-existent attributes and it won't be reported):
  ```ksy
    enum_val:
      value: int_val # <- manually check for validity
      enum: animal
  ```

---


> But, successfully parsed via Kaitai Web IDE devel

This is most likely only because the JS build of the compiler (which the Web IDE uses) ignores errors that come from [`TypeValidator`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/54691da3f80162b0b1f7cdc120fbbf244daf288b/shared/src/main/scala/io/kaitai/struct/precompile/TypeValidator.scala#L20) (which flags type mismatches in expressions). It should be fixed in https://github.com/kaitai-io/kaitai_struct_compiler/commit/8913518145cb1dc6efb3b6b40d115cb0a256c813, and I already triggered the CI including that commit so that a [new version of `kaitai-struct-compiler`](https://www.npmjs.com/package/kaitai-struct-compiler/v/0.10.0-SNAPSHOT20220621.211648.0a3dcbfb) in the `npm` registry got published, but the pipeline responsible for updating the devel Web IDE (https://app.travis-ci.com/github/kaitai-io/kaitai_struct_webide) apparently wasn't triggered from the main pipeline, despite the main pipeline [claims it was](https://app.travis-ci.com/github/kaitai-io/kaitai_struct/jobs/574555507#L1220). I have to look into it.

**Comment by cso-idn-player** [comment]
> They're not implicitly converted between each other

Ah, that's the catch.
Thank you!

Tested with this test case:
```
meta:
  id: aaa
seq:
  - id: foo
    type: bar(_index)
    repeat: expr
    repeat-expr: 2
types:
  bar:
    params:
      - id: param_1
        type: s4
    instances:
      enum_val:
        value: param_1
        enum: animal
enums:
  animal:
    0: horse
    1: dolphin
```

Result:
```json
{
  "foo": [
    {
      "param1": 0,
      "enumVal": { "name": "HORSE", "value": 0 }
    },
    {
      "param1": 1,
      "enumVal": { "name": "DOLPHIN", "value": 1 }
    }
  ]
}
```
